/*
 * Advanced Clinical Calculators
 * Evidence register: docs/clinical-calculator-evidence.md
 * Last clinical review: 2026-07-22
 * Educational simulation only. Not a prescribing engine.
 */

const CALCULATOR_REFERENCES={
  ASC1:{label:'2026 ACC/AHA Multisociety Dyslipidemia Guideline',url:'https://www.ahajournals.org/doi/10.1161/CIR.0000000000001423'},
  ASC2:{label:'Khan et al. PREVENT derivation and validation',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC10910659/'},
  ASC3:{label:'AHA official PREVENT overview',url:'https://professional.heart.org/en/guidelines-and-statements/about-prevent-calculator'},
  ASC4:{label:'ClinCalc PREVENT comparison',url:'https://clincalc.com/cardiology/PREVENT/'},
  DM1:{label:'ADA 2026 Pharmacologic Approaches to Glycemic Treatment',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC12690185/'},
  DM2:{label:'ADA 2026 type 2 medication decision algorithm',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC12690185/figure/F4/'},
  DM3:{label:'ADA 2026 injectable intensification algorithm',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC12690185/figure/F5/'},
  DM4:{label:'ADA 2026 Glycemic Goals and Hypoglycemia',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC12690178/'},
  DM5:{label:'ADA 2026 Cardiovascular Disease and Risk Management',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC12690187/'},
  DM6:{label:'ADA 2026 Chronic Kidney Disease',url:'https://doi.org/10.2337/dc26-S011'},
  VAN1:{label:'ASHP/IDSA/PIDS/SIDP vancomycin consensus guideline',url:'https://www.idsociety.org/practice-guideline/vancomycin/'},
  VAN2:{label:'ASHP full vancomycin guideline PDF',url:'https://www.ashp.org/-/media/assets/policy-guidelines/docs/therapeutic-guidelines/therapeutic-guidelines-monitoring-vancomycin-ASHP-IDSA-PIDS.pdf'},
  VAN3:{label:'Sawchuk–Zaske two-level PK method',url:'https://pubmed.ncbi.nlm.nih.gov/950590/'},
  VAN4:{label:'ClinCalc vancomycin comparison',url:'https://clincalc.com/vancomycin/'},
  REN1:{label:'KDIGO 2024 CKD Guideline',url:'https://kdigo.org/wp-content/uploads/2024/03/KDIGO-2024-CKD-Guideline.pdf'},
  REN2:{label:'NIDDK adult GFR equations',url:'https://www.niddk.nih.gov/research-funding/research-programs/kidney-clinical-research-epidemiology/laboratory/glomerular-filtration-rate-equations/adults'},
  REN3:{label:'NIDDK drug dosing in CKD',url:'https://www.niddk.nih.gov/research-funding/research-programs/kidney-clinical-research-epidemiology/laboratory/ckd-drug-dosing-providers'},
  REN4:{label:'FDA renal-impairment PK guidance',url:'https://www.fda.gov/regulatory-information/search-fda-guidance-documents/pharmacokinetics-patients-impaired-renal-function-study-design-data-analysis-and-impact-dosing'},
  REN5:{label:'Inker et al. 2021 race-free CKD-EPI equations',url:'https://pubmed.ncbi.nlm.nih.gov/34554658/'},
  REN6:{label:'Cockcroft and Gault 1976',url:'https://pubmed.ncbi.nlm.nih.gov/1244564/'},
  REN7:{label:'KDIGO 2012 Acute Kidney Injury Guideline',url:'https://kdigo.org/wp-content/uploads/2016/10/KDIGO-2012-AKI-Guideline-English.pdf'},
  REN8:{label:'KDIGO AKI definition and classification',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC4089595/'},
  REN9:{label:'Adult baseline-creatinine estimation review',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC9325517/'},
  REN10:{label:'Urine-output assessment in AKI',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC6985265/'},
  OP1:{label:'CDC Opioid Prescribing Guideline 2022',url:'https://www.cdc.gov/mmwr/volumes/71/rr/rr7103a1.htm'},
  OP2:{label:'VA/DoD Opioid Guideline 2022',url:'https://www.healthquality.va.gov/guidelines/Pain/cot/VADoDOpioidsCPG.pdf'},
  OP3:{label:'FDA fentanyl transdermal labeling',url:'https://dailymed.nlm.nih.gov/dailymed/lookup.cfm?setid=e15a7e9b-8025-49dd-9a6d-bafcccf1959f'},
  OP5:{label:'Merck Manual equianalgesic table',url:'https://www.merckmanuals.com/professional/multimedia/table/equianalgesic-doses-of-opioid-analgesics'},
  OP6:{label:'ClinCalc opioid comparison (legacy secondary source)',url:'https://clincalc.com/opioids/'},
  OP7:{label:'FDA morphine immediate-release labeling',url:'https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5ceb3205-2f8d-4ba3-9f27-dc328bab4fa1'},
  OP8:{label:'FDA oxycodone immediate-release labeling',url:'https://dailymed.nlm.nih.gov/dailymed/lookup.cfm?setid=e73897d6-b920-4300-a564-5dbc9c8e9fe9'},
  OP9:{label:'FDA hydromorphone immediate-release labeling',url:'https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d6b40e39-a57e-402c-b4f6-7041e832f837'},
  LAB1:{label:'NCBI Clinical Methods: Serum Chloride, Bicarbonate, and Anion Gap',url:'https://www.ncbi.nlm.nih.gov/books/NBK309/'},
  LAB2:{label:'NCBI Bookshelf: Calcium and albumin interpretation',url:'https://www.ncbi.nlm.nih.gov/books/NBK279022/'},
  PHEN1:{label:'FDA phenytoin prescribing information via DailyMed',url:'https://dailymed.nlm.nih.gov/dailymed/search.cfm?query=phenytoin'},
  HEP1:{label:'FDA heparin prescribing information via DailyMed',url:'https://dailymed.nlm.nih.gov/dailymed/search.cfm?query=heparin'},
  BMI1:{label:'CDC Adult BMI Categories',url:'https://www.cdc.gov/bmi/adult-calculator/bmi-categories.html'}
};

function calculatorReferenceLinks(ids){
  return (ids||[]).map(function(id){const r=CALCULATOR_REFERENCES[id];return r?`<a class="calc-ref" href="${r.url}" target="_blank" rel="noopener">${r.label}</a>`:'';}).join('');
}
function calculatorStatus(label,tone){return `<span class="calc-status ${tone||''}">${label}</span>`;}
function yesNoOptions(){return '<option value="0">No</option><option value="1">Yes</option>';}
function opioidOptions(includeNone){return `${includeNone?'<option value="none">None</option>':''}<option value="codeine">Codeine PO (mg/day)</option><option value="hydrocodone">Hydrocodone PO (mg/day)</option><option value="hydromorphone">Hydromorphone PO (mg/day)</option><option value="methadone">Methadone PO (mg/day)</option><option value="morphine">Morphine PO (mg/day)</option><option value="oxycodone">Oxycodone PO (mg/day)</option><option value="oxymorphone">Oxymorphone PO (mg/day)</option><option value="tapentadol">Tapentadol PO (mg/day)</option><option value="tramadol">Tramadol PO (mg/day)</option><option value="fentanyl_patch">Fentanyl patch (mcg/hr)</option>`;}
function rotationOptions(){return '<option value="morphine">Morphine PO</option><option value="oxycodone">Oxycodone PO</option><option value="hydromorphone">Hydromorphone PO</option>';}

function calculatorConceptButton(key){return `<button type="button" class="btn ghost sm calculator-concept-btn" onclick="openCalculatorConcept('${key}')">Clinical Concept</button>`;}
const CALCULATOR_CONCEPTS={
  ascvd:{title:'PREVENT-ASCVD',formula:'Sex-specific logistic equations estimate 10-year ASCVD risk; the 30-year model adds the published squared-age term for adults age 30–59.',why:'Age and interacting cardiovascular predictors are centered and transformed, multiplied by validated coefficients, summed as log odds, and converted to absolute risk. The model estimates risk rather than diagnosing atherosclerosis.',important:'Absolute risk helps scale the expected benefit of preventive therapy. It must remain subordinate to treatment groups that bypass calculated risk, including clinical ASCVD and severe hypercholesterolemia.',interpretation:['Use only within the published input ranges and a stable clinical state.','Read 10-year risk using current PREVENT categories, then apply independent pathways, risk enhancers, and selective CAC.','A result is a shared-decision input, not an automatic prescription.'],limits:['Do not use during AKI or with implausible lipid values.','Clinical or known subclinical ASCVD, LDL-C ≥190 mg/dL, and confirmed FH use separate pathways.'],refs:['ASC1','ASC2','ASC3']},
  insulin:{title:'Adult Type 2 Insulin Arithmetic',formula:'Basal start: 10 units/day or 0.1–0.2 units/kg/day. First prandial: 4 units or 10% of basal. Example basal titration: +2 units every 3 days without hypoglycemia.',why:'Weight-based arithmetic provides a conservative exposure range while glucose patterns determine whether basal or meal coverage is the unresolved problem.',important:'Insulin is high alert. Showing the arithmetic transparently helps detect overbasalization and prevents a calculator from turning an educational estimate into a prescription.',interpretation:['Severe symptomatic or catabolic hyperglycemia can support insulin consideration after crisis and diabetes type are assessed.','Unexplained hypoglycemia stops initiation and intensification arithmetic.','When fasting glucose is controlled but A1C remains high, evaluate postmeal patterns rather than repeatedly increasing basal insulin.'],limits:['Adult ambulatory type 2 diabetes only.','Excludes pregnancy, pediatrics, type 1 diabetes, pumps/AID, DKA/HHS, ICU, and inpatient protocols.'],refs:['DM1','DM3','DM4']},
  vancomycin:{title:'Two-Level Vancomycin AUC',formula:'k = ln(C1/C2)/(t2−t1); Vd = [R0×(1−e^(−k×tinf))] / {k×[Cmax−Cmin×e^(−k×tinf)]}; CL = k×Vd; AUC24 = total daily dose/CL.',why:'Two timed concentrations define a patient-specific elimination slope. Extrapolated peak and trough support a one-compartment volume and clearance estimate, which converts daily dose into exposure.',important:'For serious invasive MRSA, AUC-guided monitoring reduces reliance on trough-only targets that may conceal excessive exposure.',interpretation:['The serious-MRSA target is AUC24/MIC 400–600 when broth-microdilution MIC is 1 mg/L.','Verify exact infusion and sample times before calculation.','A prior AUC does not remain valid after renal function changes.'],limits:['Requires near steady state and reasonably stable clearance.','Not Bayesian and not a durable regimen generator during AKI.'],refs:['VAN1','VAN2','VAN3']},
  trough:{title:'Early Trough Extrapolation',formula:'True trough = measured concentration × e^(−k×hours early), where k = 0.693/patient-specific half-life.',why:'First-order elimination projects the measured concentration forward to the scheduled interval end.',important:'A level drawn early can look higher than the true trough. Correcting timing prevents a sampling error from driving an unnecessary dose change.',interpretation:['Use a patient-specific elimination rate from reliable prior kinetics.','Treat the corrected value within the indication-specific monitoring framework.'],limits:['Do not substitute a population half-life when clearance is changing.','Do not force a 15–20 mg/L trough for serious MRSA when AUC is available.'],refs:['VAN1','VAN2']},
  renal:{title:'Cockcroft–Gault and 2021 CKD-EPI',formula:'CrCl = [(140−age)×weight]/(72×SCr), ×0.85 for female sex. Absolute eGFR = indexed eGFR×BSA/1.73.',why:'Cockcroft–Gault estimates creatinine clearance using age, body size, SCr, and a historical sex coefficient. CKD-EPI estimates GFR from validated nonlinear biomarker relationships.',important:'Drug labels do not all use the same kidney metric. A clinically correct dose review begins by matching the equation and body-size convention to the label or protocol.',interpretation:['CKD staging uses indexed eGFR; selected dosing workflows may require absolute mL/min.','Show actual, IBW, and AdjBW0.4 estimates only when the body-size assumptions apply.','Near consequential cutoffs, use combined biomarkers, measured GFR, or TDM when appropriate.'],limits:['Static estimates are suppressed during AKI or rapidly changing SCr.','A GFR category alone does not diagnose CKD; chronicity, cause, and albuminuria matter.'],refs:['REN1','REN2','REN3','REN5','REN6']},
  aki:{title:'KDIGO AKI Staging',formula:'AKI: SCr rise ≥0.3 mg/dL/48 h, SCr ≥1.5× baseline/7 d, or UO <0.5 mL/kg/h for 6 h. Report the highest component stage.',why:'Serum creatinine and urine output detect different manifestations of acute kidney dysfunction. The highest qualifying component controls because discordant criteria can occur.',important:'AKI staging changes monitoring intensity and invalidates false precision from steady-state renal equations and durable drug regimens.',interpretation:['Use a measured stable baseline when available.','Calculate urine output from documented volume, weight, and a contiguous interval.','Evaluate etiology, nephrotoxins, drug accumulation, electrolytes, acid-base status, and perfusion separately.'],limits:['Does not infer a missing baseline or recommend RRT.','The 2026 AKI/AKD update was still draft at the review date; KDIGO 2012 remains the finalized source.'],refs:['REN7','REN8','REN9','REN10']},
  mme:{title:'Morphine Milligram Equivalents',formula:'Total MME/day = Σ(total daily opioid dose × CDC conversion factor).',why:'A common morphine-equivalent scale permits rough comparison of current opioid exposure across supported products.',important:'MME is a risk-context tool. It can trigger closer follow-up, overdose education, co-sedative review, and naloxone planning without acting as a rigid ceiling.',interpretation:['Use actual representative 24-hour consumption.','Review sedation, respiratory risk, organ function, indication, and co-sedatives at every exposure level.'],limits:['Never reverse CDC MME factors to create an opioid-rotation dose.','Fentanyl factor is formulation-specific; methadone conversion is nonlinear and specialist-led.'],refs:['OP1','OP2','OP3']},
  rotation:{title:'Limited Oral Opioid Rotation',formula:'Raw target dose = source daily dose × target table dose/source table dose; educational estimate = raw dose ×0.5.',why:'An equianalgesic table supplies a rough cross-drug ratio. A conservative reduction acknowledges incomplete cross-tolerance and patient variability.',important:'Separating raw arithmetic from the final prescription makes visible what the calculator cannot decide: formulation, interval, rounding, rescue plan, monitoring, and patient-specific reduction.',interpretation:['Use one stable oral immediate-release source regimen and actual 24-hour use.','Reassess pain, function, toxicity, organ function, interactions, and goals before any switch.'],limits:['Excludes methadone, fentanyl, buprenorphine, OUD, ER/LA, parenteral/PCA/neuraxial routes, unstable use, organ impairment, and co-sedatives.','No schedule, quantity, taper, or prescription is generated.'],refs:['OP1','OP5','OP7','OP8','OP9']},
  anion:{title:'Anion Gap',formula:'AG = Na − (Cl + HCO₃). Albumin-corrected AG = AG + 2.5×(4−albumin).',why:'Measured sodium represents major extracellular cations while chloride and bicarbonate represent major measured anions. Their difference estimates unmeasured anions; low albumin can mask that gap.',important:'The result helps structure an acid-base differential and can identify an otherwise hidden accumulation of unmeasured acids.',interpretation:['Compare with the local laboratory reference interval and the clinical acid-base picture.','Use albumin correction as an estimate, not a substitute for blood gas and full evaluation.'],limits:['Does not diagnose the cause of acidosis.','Lab methods and reference intervals vary by institution.'],refs:['LAB1']},
  calcium:{title:'Albumin-Corrected Calcium',formula:'Corrected calcium = measured total calcium + 0.8×(4−albumin).',why:'A substantial portion of total calcium is albumin bound, so low albumin can lower total calcium without an equivalent fall in ionized calcium.',important:'The estimate can prevent reflex treatment of an apparently low total calcium while the definitive physiologic value remains ionized calcium.',interpretation:['Use ionized calcium when the decision is consequential or binding is abnormal.'],limits:['Correction formulas are imperfect in critical illness, kidney disease, acid-base disturbance, and severe hypoalbuminemia.'],refs:['LAB2']},
  phenytoin:{title:'Corrected Total Phenytoin',formula:'Adjusted concentration = measured total/[coefficient×albumin +0.1].',why:'Phenytoin is highly albumin bound. Hypoalbuminemia and kidney dysfunction increase the free fraction, so a low total level can coexist with therapeutic or toxic free exposure.',important:'The estimate prevents automatic escalation from a misleading total concentration.',interpretation:['Use the result only as a screening estimate and evaluate symptoms, timing, interactions, and steady state.'],limits:['Obtain a measured free phenytoin level for clinical decisions in renal/hepatic disease or major protein-binding changes.'],refs:['PHEN1']},
  heparin:{title:'Heparin Infusion Pump Rate',formula:'mL/hour = ordered units/kg/hour × weight kg ÷ concentration units/mL.',why:'Dimensional analysis cancels kg and units, leaving the pump rate in mL/hour.',important:'Writing every unit prevents tenfold infusion errors with a high-alert medication.',interpretation:['Verify documented weight, standardized concentration, indication-specific protocol, and monitoring assay.'],limits:['Does not choose the therapeutic dose or titration nomogram.','Local protocol and independent checks govern the final pump setting.'],refs:['HEP1']},
  bmi:{title:'Body Mass Index',formula:'BMI = weight kg/(height m)².',why:'Dividing weight by squared height provides a population-level index of weight relative to stature.',important:'BMI can provide body-size context but should not automatically determine a drug-dosing weight or diagnosis.',interpretation:['Interpret with clinical context, body composition, and the purpose of measurement.'],limits:['Not a direct measure of adiposity, muscle mass, or medication clearance.'],refs:['BMI1']}
};
var CALCULATOR_CONCEPT_RETURN_FOCUS=null;
function calculatorConceptHTML(key){const c=CALCULATOR_CONCEPTS[key];if(!c)return '';return `<div class="calculator-concept-head"><div><span class="concept-kicker">Formula concept</span><h3 id="calculatorConceptTitle">${c.title}</h3><p>${c.formula}</p></div><button class="btn ghost sm" id="calculatorConceptClose" onclick="closeCalculatorConcept()">Close</button></div><div class="calculator-concept-body"><section><h4>Why the formula works</h4><p>${c.why}</p></section><section><h4>Why it matters</h4><p>${c.important}</p></section><section><h4>How to interpret it</h4><ul>${c.interpretation.map(x=>`<li>${x}</li>`).join('')}</ul></section><section><h4>Limits and safety stops</h4><ul>${c.limits.map(x=>`<li>${x}</li>`).join('')}</ul></section><section class="calculator-concept-sources"><h4>Guideline and primary sources</h4><div class="calc-refs">${calculatorReferenceLinks(c.refs)}</div><p>Last clinical review: 2026-07-22. Verify the complete source and local protocol before clinical use.</p></section></div>`;}
function calculatorConceptKeydown(e){const ov=document.getElementById('calculatorConceptOv');if(!ov)return;if(e.key==='Escape'){e.preventDefault();closeCalculatorConcept();return;}trapCalculatorFocus(e,ov);}
function closeCalculatorConcept(restore=true){const target=CALCULATOR_CONCEPT_RETURN_FOCUS,ov=document.getElementById('calculatorConceptOv');if(ov)ov.remove();document.removeEventListener('keydown',calculatorConceptKeydown);CALCULATOR_CONCEPT_RETURN_FOCUS=null;if(restore&&target&&target.isConnected)setTimeout(()=>target.focus(),20);}
function openCalculatorConcept(key){const c=CALCULATOR_CONCEPTS[key];if(!c)return;closeCalculatorConcept(false);CALCULATOR_CONCEPT_RETURN_FOCUS=document.activeElement;const ov=document.createElement('div');ov.className='calc-practice-ov';ov.id='calculatorConceptOv';ov.innerHTML=`<div class="calc-practice-card calculator-concept-card" role="dialog" aria-modal="true" aria-labelledby="calculatorConceptTitle">${calculatorConceptHTML(key)}</div>`;document.getElementById('calcToolOv')?.appendChild(ov)||document.getElementById('app').appendChild(ov);document.addEventListener('keydown',calculatorConceptKeydown);setTimeout(()=>document.getElementById('calculatorConceptClose')?.focus(),20);}

function advancedCalculatorHTML(){return `
  <section class="calc-tool calc-advanced formula-workbench" data-tool="ascvd">
    <header class="formula-workbench-head"><div><span class="calc-kicker">Cardiovascular risk formula</span><h4>PREVENT-ASCVD</h4></div><div>${calculatorStatus('2026 ACC/AHA','current')}${calculatorConceptButton('ascvd')}</div></header>
    <div class="formula-workbench-formula"><b>Risk = e<sup>log odds</sup> ÷ (1 + e<sup>log odds</sup>)</b><span>10-year risk at age 30–79 · 30-year risk at age 30–59</span></div>
    <div class="calc-field-grid calc-field-grid-4">
      <div><label for="pv_age">Age</label><input id="pv_age" type="number" value="50" min="30" max="79"></div><div><label for="pv_sex">Sex</label><select id="pv_sex"><option value="f">Female</option><option value="m">Male</option></select></div><div><label for="pv_tc">Total cholesterol mg/dL</label><input id="pv_tc" type="number" value="200"></div><div><label for="pv_hdl">HDL-C mg/dL</label><input id="pv_hdl" type="number" value="45"></div>
      <div><label for="pv_ldl">LDL-C mg/dL</label><input id="pv_ldl" type="number" value="128"></div><div><label for="pv_sbp">Systolic BP mmHg</label><input id="pv_sbp" type="number" value="160"></div><div><label for="pv_egfr">Stable eGFR</label><input id="pv_egfr" type="number" value="90"></div><div><label for="pv_dm">Diabetes</label><select id="pv_dm">${yesNoOptions()}</select></div>
      <div><label for="pv_smoke">Current smoker</label><select id="pv_smoke">${yesNoOptions()}</select></div><div><label for="pv_bptx">Antihypertensive therapy</label><select id="pv_bptx"><option value="1">Yes</option><option value="0">No</option></select></div><div><label for="pv_statin">Currently taking statin</label><select id="pv_statin">${yesNoOptions()}</select></div><div><label for="pv_cac">CAC result</label><select id="pv_cac"><option value="none">Not measured</option><option value="zero">CAC 0</option><option value="1_99">CAC 1–99 and &lt;75th percentile</option><option value="100_299">CAC 100–299 or ≥75th percentile</option><option value="300_999">CAC 300–999</option><option value="1000">CAC ≥1000</option></select></div>
    </div>
    <details class="formula-modifiers"><summary>Clinical modifiers and independent pathways</summary><div class="calc-field-grid calc-field-grid-4"><div><label for="pv_enhancer">Other risk enhancer</label><select id="pv_enhancer">${yesNoOptions()}</select></div><div><label for="pv_family">Strong premature family history</label><select id="pv_family">${yesNoOptions()}</select></div><div><label for="pv_fh">Confirmed/probable FH</label><select id="pv_fh">${yesNoOptions()}</select></div><div><label for="pv_ckd">Confirmed CKD ≥3 months</label><select id="pv_ckd">${yesNoOptions()}</select></div><div><label for="pv_aki">Current AKI/nonsteady renal function</label><select id="pv_aki">${yesNoOptions()}</select></div><div><label for="pv_hiv">HIV on stable ART</label><select id="pv_hiv">${yesNoOptions()}</select></div><div><label for="pv_ascvd">Clinical ASCVD</label><select id="pv_ascvd">${yesNoOptions()}</select></div><div><label for="pv_subclinical">Known subclinical ASCVD</label><select id="pv_subclinical">${yesNoOptions()}</select></div></div></details>
    <div class="formula-action-row"><button class="btn sm" onclick="calcPreventASCVD()">Calculate risk</button><div class="calc-result" id="pv_out" role="status" aria-live="polite"></div></div>
    <div id="pv_flow">${statinDecisionTreeHTML()}</div>
  </section>

  <section class="calc-tool calc-advanced formula-workbench" data-tool="diabetes">
    <header class="formula-workbench-head"><div><span class="calc-kicker">Adult ambulatory type 2 diabetes</span><h4>Medication Decision Path and Insulin</h4></div><div>${calculatorStatus('No automatic prescription','')}${calculatorConceptButton('insulin')}</div></header>
    <div class="formula-workbench-formula"><b>Comorbidities and safety determine the pathway before dose arithmetic</b><span>Basal: 10 units/day or 0.1–0.2 units/kg/day · first prandial: 4 units or 10% of current basal</span></div>
    <div class="calc-field-grid calc-field-grid-4"><div><label for="di_type">Diabetes type</label><select id="di_type"><option value="t2">Confirmed type 2</option><option value="uncertain">Type 1/insulin deficiency suspected</option></select></div><div><label for="di_a1c">Current A1C %</label><input id="di_a1c" type="number" step="0.1" value="8.4"></div><div><label for="di_goal">Individualized goal %</label><input id="di_goal" type="number" step="0.1" value="7"></div><div><label for="di_glucose">Current glucose mg/dL</label><input id="di_glucose" type="number" value="190"></div><div><label for="di_egfr">Stable eGFR</label><input id="di_egfr" type="number" value="75"></div><div><label for="di_symptoms">Symptoms/catabolism</label><select id="di_symptoms">${yesNoOptions()}</select></div><div><label for="di_crisis">DKA/HHS suspected</label><select id="di_crisis">${yesNoOptions()}</select></div></div>
    <details class="formula-modifiers"><summary>Comorbidities and treatment priorities</summary><div class="calc-field-grid calc-field-grid-4"><div><label for="di_ascvd">Established ASCVD / high risk</label><select id="di_ascvd">${yesNoOptions()}</select></div><div><label for="di_hf">Heart failure</label><select id="di_hf">${yesNoOptions()}</select></div><div><label for="di_hfpef_obesity">Obesity with symptomatic HFpEF confirmed</label><select id="di_hfpef_obesity">${yesNoOptions()}</select></div><div><label for="di_ckd">Confirmed CKD</label><select id="di_ckd">${yesNoOptions()}</select></div><div><label for="di_albuminuria">Confirmed persistent UACR ≥30 mg/g</label><select id="di_albuminuria">${yesNoOptions()}</select></div><div><label for="di_weight_priority">Obesity / weight reduction priority</label><select id="di_weight_priority">${yesNoOptions()}</select></div><div><label for="di_hypo">High hypoglycemia risk</label><select id="di_hypo">${yesNoOptions()}</select></div><div><label for="di_cost">Cost/access dominates</label><select id="di_cost">${yesNoOptions()}</select></div></div></details>
    <div class="formula-action-row"><button class="btn sm" onclick="calcDiabetesPathway()">Build medication pathway</button><div class="calc-result" id="di_out" role="status" aria-live="polite"></div></div>
    <div id="di_flow">${diabetesDecisionTreeHTML()}</div>
    <section class="formula-subworkbench" aria-labelledby="insulinWorksheetTitle"><div class="subtool-title"><div><span class="calc-kicker">Educational insulin worksheet</span><h5 id="insulinWorksheetTitle">Basal and First-Prandial Arithmetic</h5></div></div><div class="calc-field-grid calc-field-grid-4"><div><label for="in_weight">Weight kg</label><input id="in_weight" type="number" step="0.1" value="75"></div><div><label for="in_basal">Current basal units/day</label><input id="in_basal" type="number" step="1" placeholder="optional"></div><div><label for="in_fasting">Typical fasting glucose</label><input id="in_fasting" type="number" value="165"></div><div><label for="in_bedtime">Typical bedtime glucose</label><input id="in_bedtime" type="number" value="220"></div><div><label for="in_hypo">Unexplained glucose &lt;70</label><select id="in_hypo">${yesNoOptions()}</select></div></div><div class="formula-action-row"><button class="btn sm" onclick="calcInsulinTeachingPlan()">Show educational range</button><div class="calc-result" id="in_out" role="status" aria-live="polite"></div></div></section>
  </section>

  <section class="calc-tool calc-advanced formula-workbench" data-tool="vancomycin">
    <header class="formula-workbench-head"><div><span class="calc-kicker">Patient-specific pharmacokinetics</span><h4>Vancomycin AUC and Trough Timing</h4></div><div>${calculatorStatus('AUC preferred for serious MRSA','current')}${calculatorConceptButton('vancomycin')}</div></header>
    <div class="formula-workbench-formula"><b>k = ln(C1/C2) ÷ (t2−t1) · AUC24 = total daily dose ÷ CL</b><span>Transparent two-level, near-steady-state model · not Bayesian</span></div>
    <div class="calc-split"><div class="calc-pane"><h5>Two-level AUC24</h5><div class="calc-field-grid calc-field-grid-4"><div><label for="va_dose">Dose mg</label><input id="va_dose" type="number" value="1000"></div><div><label for="va_tau">Interval h</label><input id="va_tau" type="number" value="12"></div><div><label for="va_tinf">Infusion h</label><input id="va_tinf" type="number" step="0.25" value="1"></div><div><label for="va_mic">MIC mg/L</label><input id="va_mic" type="number" step="0.25" value="1"></div><div><label for="va_c1">Level 1 mg/L</label><input id="va_c1" type="number" step="0.1" value="28"></div><div><label for="va_t1">Level 1 h after infusion</label><input id="va_t1" type="number" step="0.25" value="1"></div><div><label for="va_c2">Level 2 mg/L</label><input id="va_c2" type="number" step="0.1" value="12"></div><div><label for="va_t2">Level 2 h after infusion</label><input id="va_t2" type="number" step="0.25" value="10.5"></div><div><label for="va_context">Indication</label><select id="va_context"><option value="serious">Serious invasive MRSA</option><option value="other">Other/noninvasive</option></select></div><div><label for="va_steady">Near steady state</label><select id="va_steady"><option value="1">Yes</option><option value="0">No</option></select></div><div><label for="va_stable">Renal function stable</label><select id="va_stable"><option value="1">Yes</option><option value="0">No</option></select></div></div><div class="calc-actions"><button class="btn sm" onclick="calcVancomycinAUC()">Estimate AUC24</button></div><div class="calc-result" id="va_out" role="status" aria-live="polite"></div></div><div class="calc-pane"><div class="subtool-title"><h5>Early trough correction</h5>${calculatorConceptButton('trough')}</div><div class="formula-mini">C<sub>trough</sub> = C<sub>measured</sub> × e<sup>−k×hours early</sup></div><div class="calc-field-grid"><div><label for="vt_level">Measured level mg/L</label><input id="vt_level" type="number" step="0.1" value="17"></div><div><label for="vt_early">Hours early</label><input id="vt_early" type="number" step="0.25" value="2"></div><div><label for="vt_half">Patient half-life h</label><input id="vt_half" type="number" step="0.1" value="8"></div><div><label for="vt_context">Clinical use</label><select id="vt_context"><option value="serious">Serious invasive MRSA</option><option value="facility">Facility-defined target</option><option value="hd">Intermittent HD predialysis</option></select></div></div><div class="calc-actions"><button class="btn sm" onclick="calcVancomycinTrough()">Correct timing</button></div><div class="calc-result" id="vt_out" role="status" aria-live="polite"></div></div></div>
  </section>

  <section class="calc-tool calc-advanced formula-workbench" data-tool="renal">
    <header class="formula-workbench-head"><div><span class="calc-kicker">Kidney estimates · label-specific metric required</span><h4>Creatinine Clearance and GFR</h4></div><div>${calculatorStatus('Stable renal function only','current')}${calculatorConceptButton('renal')}</div></header>
    <div class="formula-workbench-formula"><b>CrCl = [(140−age) × weight] ÷ (72 × SCr) · female ×0.85</b><span>2021 CKD-EPI eGFR and absolute BSA-adjusted eGFR shown alongside</span></div>
    <div class="calc-field-grid calc-field-grid-4"><div><label for="rn_age">Age</label><input id="rn_age" type="number" value="72"></div><div><label for="rn_sex">Sex</label><select id="rn_sex" onchange="updateCockcroftWeightOptions()"><option value="f">Female</option><option value="m">Male</option></select></div><div><label for="rn_height">Height cm</label><input id="rn_height" type="number" value="160" oninput="updateCockcroftWeightOptions()"></div><div><label for="rn_weight">Actual weight kg</label><input id="rn_weight" type="number" value="95" oninput="updateCockcroftWeightOptions()"></div><div><label for="rn_scr">SCr mg/dL</label><input id="rn_scr" type="number" step="0.1" value="1.2"></div><div><label for="rn_cys">Cystatin C mg/L</label><input id="rn_cys" type="number" step="0.1" placeholder="optional"></div><div><label for="rn_aki">Unstable SCr/AKI</label><select id="rn_aki">${yesNoOptions()}</select></div><div><label for="rn_preg">Pregnant</label><select id="rn_preg">${yesNoOptions()}</select></div><div><label for="rn_cg_weight">CG weight convention</label><select id="rn_cg_weight"><option value="all">Show all; no selection</option><option value="actual">Actual per label/protocol</option><option value="ideal">IBW per protocol</option><option value="adjusted">AdjBW0.4 per obesity protocol</option></select></div></div>
    <div class="formula-action-row"><button class="btn sm" onclick="calcRenalFunction()">Calculate estimates</button><div class="calc-result" id="rn_out" role="status" aria-live="polite"></div></div>
    <section class="formula-subworkbench"><div class="subtool-title"><div><span class="calc-kicker">Acute kidney injury</span><h5>KDIGO Recognition and Staging</h5></div>${calculatorConceptButton('aki')}</div><div class="formula-mini">SCr change + urine output + new RRT · highest component stage controls</div><div class="calc-field-grid calc-field-grid-4"><div><label for="ak_base_source">Baseline source</label><select id="ak_base_source"><option value="measured">Measured stable baseline</option><option value="unknown">Unknown</option></select></div><div><label for="ak_baseline">Baseline SCr</label><input id="ak_baseline" type="number" step="0.01" value="1"></div><div><label for="ak_current">Current SCr</label><input id="ak_current" type="number" step="0.01" value="1.4"></div><div><label for="ak_scr_hours">SCr interval h</label><input id="ak_scr_hours" type="number" value="30"></div><div><label for="ak_weight">Weight kg</label><input id="ak_weight" type="number" step="0.1" placeholder="optional UO"></div><div><label for="ak_urine">Urine volume mL</label><input id="ak_urine" type="number" placeholder="optional"></div><div><label for="ak_uo_hours">Urine interval h</label><input id="ak_uo_hours" type="number" placeholder="optional"></div><div><label for="ak_anuria">Anuria h</label><input id="ak_anuria" type="number" value="0"></div><div><label for="ak_rrt">New RRT</label><select id="ak_rrt">${yesNoOptions()}</select></div></div><div class="formula-action-row"><button class="btn sm" onclick="calcKdigoAki()">Check KDIGO stage</button><div class="calc-result" id="ak_out" role="status" aria-live="polite"></div></div></section>
  </section>

  <section class="calc-tool calc-advanced formula-workbench" data-tool="opioid">
    <header class="formula-workbench-head"><div><span class="calc-kicker">Risk comparison and bounded rotation arithmetic</span><h4>Opioid MME and Oral Rotation</h4></div><div>${calculatorStatus('Educational only','')}${calculatorConceptButton('mme')}</div></header>
    <div class="formula-workbench-formula"><b>Total MME/day = Σ(daily dose × CDC factor)</b><span>MME is never reversed to generate a rotation dose</span></div>
    <details class="formula-modifiers"><summary>Required scope and safety check</summary><div class="calc-field-grid calc-field-grid-4"><div><label for="og_setting">Care setting</label><select id="og_setting" onchange="invalidateOpioidGate()"><option value="outpatient">Adult outpatient</option><option value="inpatient">Inpatient/monitored</option></select></div><div><label for="og_duration">Pain duration</label><select id="og_duration" onchange="invalidateOpioidGate()"><option value="acute">Acute &lt;1 month</option><option value="subacute">Subacute 1–3 months</option><option value="chronic">Chronic &gt;3 months</option></select></div><div><label for="og_status">Opioid status</label><select id="og_status" onchange="invalidateOpioidGate()"><option value="naive">Opioid-naive</option><option value="stable">Stable oral IR use</option><option value="unstable">Variable/escalating use</option></select></div><div><label for="og_formulation">Formulation</label><select id="og_formulation" onchange="invalidateOpioidGate()"><option value="ir">Oral immediate-release</option><option value="erla">ER/LA</option><option value="other">Parenteral/PCA/neuraxial</option></select></div><div><label for="og_organ">Renal/hepatic function</label><select id="og_organ" onchange="invalidateOpioidGate()"><option value="stable">Stable, no material impairment</option><option value="impaired">Stable impairment</option><option value="unstable">Unstable/AKI/decompensated</option></select></div><div><label for="og_cosedative">CNS depressant</label><select id="og_cosedative" onchange="invalidateOpioidGate()">${yesNoOptions()}</select></div><div><label for="og_respiratory">Respiratory/overdose risk</label><select id="og_respiratory" onchange="invalidateOpioidGate()">${yesNoOptions()}</select></div><div><label for="og_excluded">Specialist-only population/opioid</label><select id="og_excluded" onchange="invalidateOpioidGate()">${yesNoOptions()}</select></div></div><div class="calc-actions"><button class="btn sm" onclick="calcOpioidDosingGate()">Review scope</button></div><div class="calc-result" id="og_out" role="status" aria-live="polite"></div><div id="og_flow">${opioidDecisionTreeHTML()}</div></details>
    <div class="calc-split"><div class="calc-pane"><h5>Daily MME</h5><div class="calc-field-grid calc-field-grid-3"><div><label for="op_drug1">Opioid 1</label><select id="op_drug1">${opioidOptions(false)}</select></div><div><label for="op_dose1">Daily dose</label><input id="op_dose1" type="number" step="0.1" value="40"></div><div><label for="op_drug2">Opioid 2</label><select id="op_drug2">${opioidOptions(true)}</select></div><div><label for="op_dose2">Daily dose</label><input id="op_dose2" type="number" step="0.1" placeholder="optional"></div><div><label for="op_drug3">Opioid 3</label><select id="op_drug3">${opioidOptions(true)}</select></div><div><label for="op_dose3">Daily dose</label><input id="op_dose3" type="number" step="0.1" placeholder="optional"></div></div><div class="calc-actions"><button class="btn sm" onclick="calcOpioidMME()">Calculate MME</button></div><div class="calc-result" id="op_out" role="status" aria-live="polite"></div></div><div class="calc-pane"><div class="subtool-title"><h5>Limited oral IR rotation</h5>${calculatorConceptButton('rotation')}</div><div class="formula-mini">Raw table equivalent × 0.5 educational cross-tolerance estimate</div><div class="calc-field-grid"><div><label for="or_from">Current opioid</label><select id="or_from">${rotationOptions()}</select></div><div><label for="or_dose">Current mg/day</label><input id="or_dose" type="number" step="0.1" value="60"></div><div><label for="or_to">Target opioid</label><select id="or_to"><option value="oxycodone">Oxycodone PO</option><option value="morphine">Morphine PO</option><option value="hydromorphone">Hydromorphone PO</option></select></div></div><div class="calc-actions"><button class="btn sm" id="or_calculate" onclick="calcOpioidRotation()" disabled>Show educational estimate</button></div><div class="calc-result" id="or_out" role="status" aria-live="polite"></div></div></div>
  </section>`;}

/* CLINICAL_CALCULATORS_LOGIC_START */
function calcReadNumber(id){const el=document.getElementById(id),v=parseFloat(String(el?.value||'').replace(/,/g,''));return Number.isFinite(v)?v:null;}
function calcReadBinary(id){return document.getElementById(id)?.value==='1'?1:0;}
function calcRound(value,digits){const p=Math.pow(10,digits??1);return Math.round(value*p)/p;}
function calcPercentFromLogit(x){return 100/(1+Math.exp(-x));}
function preventASCVD10Base(age,sex,tc,hdl,sbp,dm,smoking,egfr,bptreat,statin){
  const mmol=function(x){return x*0.02586;},a=(age-55)/10,nonhdl=(mmol(tc)-mmol(hdl))-3.5,h=(mmol(hdl)-1.3)/0.3,slo=(Math.min(sbp,110)-110)/20,shi=(Math.max(sbp,110)-130)/20,gl=(Math.min(egfr,60)-60)/-15,gh=(Math.max(egfr,60)-90)/-15;
  let x;
  if(sex==='f'){
    x=-3.819975+0.719883*a+0.1176967*nonhdl-0.151185*h-0.0835358*slo+0.3592852*shi+0.8348585*dm+0.4831078*smoking+0.4864619*gl+0.0397779*gh+0.2265309*bptreat-0.0592374*statin-0.0395762*bptreat*shi+0.0844423*statin*nonhdl-0.0567839*a*nonhdl+0.0325692*a*h-0.1035985*a*shi-0.2417542*a*dm-0.0791142*a*smoking-0.1671492*a*gl;
  }else{
    x=-3.500655+0.7099847*a+0.1658663*nonhdl-0.1144285*h-0.2837212*slo+0.3239977*shi+0.7189597*dm+0.3956973*smoking+0.3690075*gl+0.0203619*gh+0.2036522*bptreat-0.0865581*statin-0.0322916*bptreat*shi+0.114563*statin*nonhdl-0.0300005*a*nonhdl+0.0232747*a*h-0.0927024*a*shi-0.2018525*a*dm-0.0970527*a*smoking-0.1217081*a*gl;
  }
  return calcPercentFromLogit(x);
}
function preventASCVD30Base(age,sex,tc,hdl,sbp,dm,smoking,egfr,bptreat,statin){
  if(age<30||age>59)return null;
  const mmol=function(x){return x*0.02586;},a=(age-55)/10,nonhdl=(mmol(tc)-mmol(hdl))-3.5,h=(mmol(hdl)-1.3)/0.3,slo=(Math.min(sbp,110)-110)/20,shi=(Math.max(sbp,110)-130)/20,gl=(Math.min(egfr,60)-60)/-15,gh=(Math.max(egfr,60)-90)/-15;
  let x;
  if(sex==='f'){
    x=-1.974074+0.4669202*a-0.0893118*a*a+0.1256901*nonhdl-0.1542255*h-0.0018093*slo+0.322949*shi+0.6296707*dm+0.268292*smoking+0.100106*gl+0.0499663*gh+0.1875292*bptreat+0.0152476*statin-0.0276123*bptreat*shi+0.0736147*statin*nonhdl-0.0521962*a*nonhdl+0.0316918*a*h-0.1046101*a*shi-0.2727793*a*dm-0.1530907*a*smoking-0.1299149*a*gl;
  }else{
    x=-1.736444+0.3994099*a-0.0937484*a*a+0.1744643*nonhdl-0.120203*h-0.0665117*slo+0.2753037*shi+0.4790257*dm+0.1782635*smoking-0.0218789*gl+0.0602553*gh+0.1421182*bptreat+0.0135996*statin-0.0218265*bptreat*shi+0.1013148*statin*nonhdl-0.0312619*a*nonhdl+0.020673*a*h-0.0920935*a*shi-0.2159947*a*dm-0.1548811*a*smoking-0.0712547*a*gl;
  }
  return calcPercentFromLogit(x);
}
function generalCardiovascularInputProblems(age,tc,hdl,ldl,sbp,egfr){const problems=[];if(age<18||age>120)problems.push('adult age 18–120');if(tc<50||tc>1000)problems.push('plausible total cholesterol 50–1000');if(hdl<5||hdl>200)problems.push('plausible HDL-C 5–200');if(ldl<0||ldl>1000)problems.push('plausible LDL-C 0–1000');if(sbp<60||sbp>260)problems.push('plausible SBP 60–260');if(egfr<1||egfr>200)problems.push('plausible eGFR 1–200');if(ldl>tc)problems.push('LDL-C not greater than total cholesterol');if(hdl>=tc)problems.push('HDL-C lower than total cholesterol');if(ldl>tc-hdl+5)problems.push('LDL-C not materially greater than non-HDL-C (5 mg/dL analytic tolerance)');return problems;}
function preventEquationInputProblems(age,tc,hdl,ldl,sbp,egfr){const problems=[];if(age<30||age>79)problems.push('age 30–79');if(tc<130||tc>320)problems.push('total cholesterol 130–320');if(hdl<20||hdl>100)problems.push('HDL-C 20–100');if(sbp<90||sbp>200)problems.push('SBP 90–200');if(egfr<15||egfr>140)problems.push('stable eGFR 15–140');if(ldl<70||ldl>189)problems.push('LDL-C 70–189 for this PREVENT pathway');return problems;}
function preventStatinDecision(input){
  const {age,sex,ldl,risk10,risk30,dm,egfr,hiv,enhancer,smoking,cac='none',known,subclinical,family,fh,confirmedCkd,aki}=input;
  if(known)return {pathway:'secondary',step:0,label:'Clinical ASCVD pathway',recommendation:'Do not use PREVENT to decide whether to treat. Use high-intensity or maximally tolerated lipid-lowering therapy with ≥50% LDL-C reduction.',goal:'LDL-C <70 and non-HDL-C <100 mg/dL; use <55/<85 for very-high-risk ASCVD.'};
  if(fh||ldl>=190)return {pathway:'severe',step:0,label:fh?'Familial hypercholesterolemia pathway':'LDL-C ≥190 mg/dL',recommendation:'Use maximally tolerated statin therapy and evaluate secondary causes and familial hypercholesterolemia; low PREVENT risk or CAC 0 must not defer treatment.',goal:'Baseline goal LDL-C <100/non-HDL-C <130; use <70/<100 with HeFH, another risk factor, or coronary calcification.'};
  if(subclinical)return {pathway:'subclinical',step:0,label:'Known subclinical atherosclerosis',recommendation:'PREVENT is not the treatment-decision engine. Apply the imaging-defined disease-burden pathway and its LDL-C goal.',goal:'Document the imaging category before selecting intensity and goal.'};
  if(aki)return {pathway:'renal-unstable',step:0,label:'Nonsteady renal function',recommendation:'Do not calculate PREVENT with an acute, nonsteady renal value. Reassess with a stable eGFR after the acute episode or use clinician judgment for an independent treatment indication.',goal:'No PREVENT estimate displayed.'};
  const conditions=[];if(age>=40&&age<=75&&dm)conditions.push('diabetes');if(age>=40&&age<=75&&confirmedCkd&&egfr>=15&&egfr<60)conditions.push('confirmed CKD stage 3–4');if(age>=40&&age<=75&&hiv)conditions.push('HIV on stable combination ART');
  const conditionDecision=function(){let detail='';if(dm)detail+=' Diabetes age 40–75 indicates at least moderate-intensity statin; multiple risk factors can support high intensity.';if(confirmedCkd&&egfr>=15&&egfr<60)detail+=' Confirmed CKD stage 3–4 supports moderate-intensity statin or moderate-intensity statin plus ezetimibe when LDL-C is 70–189.';if(hiv)detail+=' HIV on stable ART has a statin recommendation, with ART–statin interactions checked separately.';return {pathway:'condition',step:1,label:'Independent treatment pathway',recommendation:`Lipid-lowering therapy is recommended for ${conditions.join(', ')} independent of the raw PREVENT threshold.${detail}`,goal:'Use the condition-specific intensity and LDL-C goal.'};};
  const cacInScope=sex==='m'?age>=40:age>=45;if(cac!=='none'&&!cacInScope)return conditions.length?conditionDecision():{pathway:'cac-scope',step:3,label:'CAC reclassification outside usual age scope',recommendation:'The generic CAC reclassification pathway is intended for men ≥40 and women ≥45 when the treatment decision remains uncertain.',goal:'Use individualized specialist interpretation rather than this rule tree.'};
  if(cac==='1000')return {pathway:'cac1000',step:3,label:'CAC ≥1000',recommendation:'Intensive lipid-lowering therapy is recommended with statin first line and ≥50% LDL-C reduction.',goal:'LDL-C <55 and non-HDL-C <85 mg/dL.'};
  if(cac==='300_999')return {pathway:'cac300',step:3,label:'CAC 300–999',recommendation:'Lipid-lowering therapy with statin first line and ≥50% LDL-C reduction is recommended; further intensification toward the lower goal is reasonable.',goal:'LDL-C <70/non-HDL-C <100; optional intensification toward <55/<85 mg/dL.'};
  if(cac==='100_299')return {pathway:'cac100',step:3,label:'CAC 100–299 or ≥75th percentile',recommendation:'Lipid-lowering therapy is recommended, with statin first line and preferably ≥50% LDL-C reduction.',goal:'LDL-C <70 and non-HDL-C <100 mg/dL.'};
  if(cac==='1_99')return {pathway:'cac1',step:3,label:'CAC 1–99 and <75th percentile',recommendation:'A moderate-intensity statin with 30–49% LDL-C reduction is reasonable.',goal:'LDL-C <100 and non-HDL-C <130 mg/dL.'};
  if(conditions.length)return conditionDecision();
  if(cac==='zero'){const exceptions=[];if(dm&&age>40)exceptions.push('diabetes after age 40');if(smoking)exceptions.push('current smoking');if(family)exceptions.push('strong premature family history');if(exceptions.length)return {pathway:'cac0-exception',step:3,label:'CAC 0 with a no-deferral exception',recommendation:`CAC 0 does not support deferring statin therapy because ${exceptions.join(', ')} is present.`,goal:'Return to the applicable clinical-risk pathway.'};return {pathway:'cac0',step:3,label:'CAC 0',recommendation:'Deferring lipid-lowering therapy may be reasonable when no exception applies; continue health-behavior counseling and consider repeat CAC in 3–7 years.',goal:'CAC 0 does not erase future reassessment or a hard treatment indication.'};}
  const category=risk10<3?'Low':risk10<5?'Borderline':risk10<10?'Intermediate':'High';
  if(risk10<3&&(ldl>=160||risk30!==null&&risk30>=10))return {pathway:risk30!==null&&risk30>=10?'longterm':'ldl-enhanced',step:2,label:'Elevated cumulative exposure',category,recommendation:'A moderate-intensity statin with 30–49% LDL-C reduction is reasonable because LDL-C is 160–189 mg/dL or 30-year PREVENT-ASCVD risk is ≥10%.',goal:'Individualize the LDL-C goal after the treatment decision.'};
  if(risk10<3)return {pathway:'low',step:4,label:'Low PREVENT risk',category,recommendation:'Health-behavior counseling is recommended; no automatic statin indication is created by the supplied values.',goal:'Reassess risk and cumulative exposure over time.'};
  if(risk10<5){const hasEnhancer=enhancer||family;return {pathway:hasEnhancer?'borderline-enhanced':'borderline',step:4,label:'Borderline PREVENT risk',category,recommendation:hasEnhancer?'A moderate-intensity statin with 30–49% LDL-C reduction is reasonable after discussion because a risk enhancer is present.':'A moderate-intensity statin with 30–49% LDL-C reduction is reasonable after clinician-patient benefit-risk discussion; review risk enhancers and use CAC only if uncertainty remains.',goal:'If therapy is started: LDL-C <100 and non-HDL-C <130 mg/dL.'};}
  if(risk10<10)return {pathway:'intermediate',step:4,label:'Intermediate PREVENT risk',category,recommendation:'At least moderate-intensity statin therapy with 30–49% LDL-C reduction is recommended; high intensity is beneficial toward the upper end.',goal:'LDL-C <100 and non-HDL-C <130 mg/dL.'};
  return {pathway:'high',step:4,label:'High PREVENT risk',category,recommendation:'High-intensity statin therapy with ≥50% LDL-C reduction is recommended unless contraindicated or not tolerated.',goal:'LDL-C <70 and non-HDL-C <100 mg/dL.'};
}
function statinDecisionTreeHTML(state){
  const current=state?.step,steps=[['Eligibility gates','Clinical or known subclinical ASCVD, LDL-C ≥190, confirmed/probable FH, and nonsteady renal function are checked before PREVENT.'],['Independent pathways','Age 40–75 with diabetes, confirmed CKD stage 3–4, or HIV on stable ART follows a treatment pathway independent of the raw score.'],['PREVENT horizons','Use validated stable inputs for 10-year risk at age 30–79 and add 30-year risk at age 30–59.'],['Refine uncertainty','Review risk enhancers and use CAC selectively when a borderline or intermediate decision remains uncertain.'],['Recommendation','Match statin intensity and LDL-C goal to the controlling pathway.']];
  return `<section class="decision-tree" aria-label="2026 ACC/AHA statin decision path"><div class="decision-tree-head"><div><b>Guideline decision path</b><span>${state?.label||'Complete the calculation to highlight the controlling branch.'}</span></div>${state?`<strong>${state.label}</strong>`:''}</div><ol>${steps.map((s,i)=>`<li class="${current===i?'active':current!==undefined&&i<current?'done':''}" ${current===i?'aria-current="step"':''}><span>${i+1}</span><div><b>${s[0]}</b><p>${s[1]}</p></div></li>`).join('')}</ol></section>`;
}
function setPreventDecision(html,state){setCalcResult('pv_out',html);const flow=document.getElementById('pv_flow');if(flow)flow.innerHTML=statinDecisionTreeHTML(state);}
function calcPreventASCVD(){
  const age=calcReadNumber('pv_age'),sex=document.getElementById('pv_sex')?.value,tc=calcReadNumber('pv_tc'),hdl=calcReadNumber('pv_hdl'),ldl=calcReadNumber('pv_ldl'),sbp=calcReadNumber('pv_sbp'),egfr=calcReadNumber('pv_egfr'),dm=calcReadBinary('pv_dm'),smoke=calcReadBinary('pv_smoke'),bptx=calcReadBinary('pv_bptx'),statin=calcReadBinary('pv_statin'),enhancer=calcReadBinary('pv_enhancer'),family=calcReadBinary('pv_family'),fh=calcReadBinary('pv_fh'),confirmedCkd=calcReadBinary('pv_ckd'),aki=calcReadBinary('pv_aki'),hiv=calcReadBinary('pv_hiv'),cac=document.getElementById('pv_cac')?.value||'none',known=calcReadBinary('pv_ascvd'),subclinical=calcReadBinary('pv_subclinical');
  if([age,tc,hdl,ldl,sbp,egfr].some(v=>v===null)){setPreventDecision('Enter all required values.');return;}
  const generalProblems=generalCardiovascularInputProblems(age,tc,hdl,ldl,sbp,egfr);if(generalProblems.length){setPreventDecision(`<b>Check implausible input.</b><br>${generalProblems.join('; ')}.`);return;}
  const base={age,sex,ldl,risk10:null,risk30:null,dm,egfr,hiv,enhancer,smoking:smoke,cac,known,subclinical,family,fh,confirmedCkd,aki},early=preventStatinDecision(base);if(['secondary','subclinical','severe','renal-unstable','condition','cac1000','cac300','cac100','cac1','cac0','cac0-exception','cac-scope'].includes(early.pathway)){setPreventDecision(`<b>${early.label}</b><br>${early.recommendation}<br><span class="calc-note">${early.goal}</span>`,early);return;}
  const problems=preventEquationInputProblems(age,tc,hdl,ldl,sbp,egfr);if(problems.length){setPreventDecision(`<b>Outside the validated PREVENT pathway.</b><br>Check: ${problems.join('; ')}. Values were not silently clamped.`);return;}
  const risk10=preventASCVD10Base(age,sex,tc,hdl,sbp,dm,smoke,egfr,bptx,statin),risk30=preventASCVD30Base(age,sex,tc,hdl,sbp,dm,smoke,egfr,bptx,statin),decision=preventStatinDecision({...base,risk10,risk30}),risk30Line=risk30===null?'':` · 30-year <b>${calcRound(risk30,1)}%</b>`;
  setPreventDecision(`10-year PREVENT-ASCVD = <b>${calcRound(risk10,1)}%</b>${risk30Line} · ${decision.category||decision.label}<br>${decision.recommendation}<br><span class="calc-note">${decision.goal}</span>`,decision);
}

function diabetesMedicationPathway(input){
  if(input.type!=='t2'||input.crisis)return {code:'EXCLUDED_URGENT_DIABETES_WORKFLOW',step:0,label:'Urgent diagnostic or crisis pathway',recommendations:['Do not use this type 2 ambulatory tool. Evaluate suspected type 1 diabetes, ketosis, DKA/HHS, and marked insulin deficiency with an appropriate urgent protocol.']};
  const recommendations=[],cardiorenal=[];
  if(input.ascvd)cardiorenal.push('Include a GLP-1 RA and/or SGLT2 inhibitor with demonstrated cardiovascular benefit, irrespective of A1C or metformin use.');
  if(input.hf||input.hfpefObesity)cardiorenal.push('Use an SGLT2 inhibitor with proven heart-failure benefit for HFrEF or HFpEF, irrespective of A1C; avoid TZDs because of fluid retention.');
  if(input.hfpefObesity)cardiorenal.push('Use a GLP-1 RA or dual GIP/GLP-1 RA with demonstrated benefit for obesity with symptomatic HFpEF when appropriate.');
  const kidneyPath=input.ckd||input.albuminuria;
  if(kidneyPath&&input.egfr>=20&&(input.egfr<=60||input.albuminuria))cardiorenal.push('Use an SGLT2 inhibitor or GLP-1 RA with demonstrated kidney/cardiovascular benefit. SGLT2 initiation is supported at eGFR ≥20; glycemic effect is reduced below 45.');
  if(kidneyPath&&input.egfr<20)cardiorenal.push('Do not newly initiate an SGLT2 inhibitor below eGFR 20. An established proven-benefit SGLT2 inhibitor may sometimes continue below 20 when tolerated and the patient is not on dialysis; use the current label and kidney plan.');
  if(kidneyPath&&input.egfr<30)cardiorenal.push('For additional glucose lowering at eGFR <30, prefer a GLP-1 RA not dependent on renal clearance; do not start metformin and discontinue it below eGFR 30.');
  recommendations.push(...cardiorenal);
  const severe=input.symptoms||input.a1c>10||input.glucose>=300;if(severe)recommendations.push('Insulin should be considered because severe hyperglycemia, symptoms/catabolism, A1C >10%, or glucose ≥300 mg/dL is present. Exclude crisis and type 1 diabetes first.');
  if(!severe&&!cardiorenal.length){const gap=input.a1c-input.goal;if(gap>=1.5)recommendations.push('A1C is ≥1.5 percentage points above goal; dual therapy or a high-potency agent will often be needed.');else recommendations.push('No cardiorenal condition dominates; choose therapy by glucose-lowering need, weight goal, hypoglycemia risk, adverse effects, preferences, and access.');}
  if(!severe)recommendations.push('When an injectable is needed without severe hyperglycemia or crisis, consider GLP-1–based therapy before insulin when appropriate.');
  if(input.weightPriority)recommendations.push('Prioritize weight-lowering therapy; tirzepatide and semaglutide have the highest ADA-listed weight efficacy.');
  if(input.hypoRisk)recommendations.push('Prefer agents with little intrinsic hypoglycemia and reassess insulin, sulfonylureas, or meglitinides.');
  if(input.cost)recommendations.push('Lower-cost metformin, sulfonylurea, TZD, or human-insulin options require explicit review of hypoglycemia, weight gain, HF, kidney function, and treatment burden.');
  if(input.egfr<45&&input.egfr>=30)recommendations.push('Do not newly initiate metformin below eGFR 45; reduce/reassess an established dose.');
  return {code:severe?'INSULIN_CONSIDERATION':cardiorenal.length?'CARDIORENAL_PRIORITY':'PERSON_CENTERED_GLYCEMIC_PATH',step:severe?2:cardiorenal.length?1:3,label:severe?'Insulin consideration after crisis exclusion':cardiorenal.length?'Cardiorenal benefit controls':'Person-centered glucose-lowering path',recommendations};
}
function diabetesDecisionTreeHTML(state){const steps=[['Confirm scope','Adult ambulatory type 2 diabetes only; suspected type 1 diabetes or DKA/HHS exits to an urgent pathway.'],['Cardiorenal priority','ASCVD, heart failure, CKD, and albuminuria can determine therapy irrespective of A1C or metformin.'],['Severe hyperglycemia','Symptoms, catabolism, A1C >10%, or glucose ≥300 mg/dL support insulin consideration.'],['Safety and preferences','Weight, hypoglycemia, organ function, treatment burden, and cost shape class choice.'],['Reassess and intensify','Review response, tolerability, adherence, CGM/BGM patterns, and cardiorenal benefit without therapeutic inertia.']];const current=state?.step;return `<section class="decision-tree" aria-label="ADA type 2 diabetes medication decision path"><div class="decision-tree-head"><div><b>ADA medication decision path</b><span>${state?.recommendations?.[0]||'Complete the inputs to highlight the controlling branch.'}</span></div>${state?`<strong>${state.code}</strong>`:''}</div><ol>${steps.map((s,i)=>`<li class="${current===i?'active':current!==undefined&&i<current?'done':''}" ${current===i?'aria-current="step"':''}><span>${i+1}</span><div><b>${s[0]}</b><p>${s[1]}</p></div></li>`).join('')}</ol></section>`;}
function calcDiabetesPathway(){const a1c=calcReadNumber('di_a1c'),goal=calcReadNumber('di_goal'),glucose=calcReadNumber('di_glucose'),egfr=calcReadNumber('di_egfr');if([a1c,goal,glucose,egfr].some(v=>v===null)||a1c<3||a1c>20||goal<3||goal>12||glucose<=0||egfr<0){setCalcResult('di_out','Enter plausible A1C, goal, glucose, and eGFR values.');return;}const state=diabetesMedicationPathway({type:document.getElementById('di_type')?.value,a1c,goal,glucose,egfr,symptoms:!!calcReadBinary('di_symptoms'),crisis:!!calcReadBinary('di_crisis'),ascvd:!!calcReadBinary('di_ascvd'),hf:!!calcReadBinary('di_hf'),hfpefObesity:!!calcReadBinary('di_hfpef_obesity'),ckd:!!calcReadBinary('di_ckd'),albuminuria:!!calcReadBinary('di_albuminuria'),weightPriority:!!calcReadBinary('di_weight_priority'),hypoRisk:!!calcReadBinary('di_hypo'),cost:!!calcReadBinary('di_cost')});setCalcResult('di_out',`<b>${state.label}</b><br>${state.recommendations.map(x=>`• ${x}`).join('<br>')}`);const flow=document.getElementById('di_flow');if(flow)flow.innerHTML=diabetesDecisionTreeHTML(state);}
function insulinTeachingPlan(input){
  if(input.type!=='t2'||input.crisis)return {code:'EXCLUDED_INSULIN_PROTOCOL',text:'This worksheet does not dose suspected type 1 diabetes, DKA/HHS, pregnancy, pediatrics, pumps, ICU, or inpatient protocol selection.'};
  const severe=input.symptoms||input.a1c>10||input.glucose>=300;
  if(input.hypo)return {code:'HYPOGLYCEMIA_SAFETY_STOP',text:`Unexplained hypoglycemia stops insulin-initiation and prandial-dose arithmetic. Treat and characterize the low-glucose pattern first, review meals, activity, alcohol, kidney function, technique, and concurrent hypoglycemia-causing drugs, and have a clinician individualize ${input.currentBasal!==null&&input.currentBasal>0?'deintensification; a 10–20% basal reduction may be considered only within that review':'the plan before any basal insulin start'}.`};
  if(input.currentBasal===null){if(!severe)return {code:'NO_AUTOMATIC_INSULIN_START',text:'No severe-hyperglycemia trigger is present. If an injectable is needed, ADA generally prefers GLP-1–based therapy before insulin when appropriate.'};const low=input.weight*0.1,high=input.weight*0.2;return {code:'BASAL_INITIATION_EDUCATION',text:`ADA basal-start options are 10 units/day or ${calcRound(low,1)}–${calcRound(high,1)} units/day (0.1–0.2 units/kg/day). These are alternatives for clinician selection, not an automatic dose. An example titration is +2 units every 3 days toward the individualized fasting target without hypoglycemia.`};}
  if(input.currentBasal<=0)return {code:'INVALID_BASAL_INPUT',text:'Current basal insulin must be positive when supplied.'};
  const drop=input.bedtime-input.fasting,postmealPattern=drop>=50||(input.fasting>=80&&input.fasting<=130&&input.a1c>input.goal);if(postmealPattern){const prandial10=input.currentBasal*0.1,basal90=input.currentBasal*0.9;return {code:'OVERBASALIZATION_REDIRECT',text:`The bedtime-to-morning differential is ${calcRound(drop,0)} mg/dL${drop>=50?', meeting the ≥50 mg/dL overbasalization signal':''}. Do not keep raising basal. Consider GLP-1–based therapy first when appropriate; if first prandial insulin is chosen, ADA options are 4 units or 10% of basal (${calcRound(prandial10,1)} units) at the largest-excursion meal.${input.a1c<8?` Because A1C is <8%, consider reducing basal by 4 units or 10% (10% gives ${calcRound(basal90,1)} units/day).`:''}`};}
  if(input.fasting>130)return {code:'BASAL_TITRATION_EDUCATION',text:'Typical fasting glucose is above the general 80–130 mg/dL target. An ADA example is +2 basal units every 3 days until the individualized fasting goal is reached without hypoglycemia; use repeated BGM/CGM patterns, not a single value.'};
  return {code:'FASTING_PATTERN_AT_GOAL',text:'The supplied fasting pattern is within the general 80–130 mg/dL range. Do not increase basal solely to lower A1C; reassess postmeal patterns, hypoglycemia, and whether noninsulin therapy should be optimized.'};
}
function calcInsulinTeachingPlan(){const weight=calcReadNumber('in_weight'),currentBasal=calcReadNumber('in_basal'),fasting=calcReadNumber('in_fasting'),bedtime=calcReadNumber('in_bedtime'),a1c=calcReadNumber('di_a1c'),goal=calcReadNumber('di_goal'),glucose=calcReadNumber('di_glucose');if([weight,fasting,bedtime,a1c,goal,glucose].some(v=>v===null)||weight<=0||fasting<=0||bedtime<=0){setCalcResult('in_out','Enter positive weight, fasting glucose, and bedtime glucose values.');return;}const plan=insulinTeachingPlan({type:document.getElementById('di_type')?.value,crisis:!!calcReadBinary('di_crisis'),symptoms:!!calcReadBinary('di_symptoms'),weight,currentBasal,fasting,bedtime,a1c,goal,glucose,hypo:!!calcReadBinary('in_hypo')});setCalcResult('in_out',`<b>${plan.code}</b><br>${plan.text}<br><span class="calc-note">Educational arithmetic only. Verify diabetes type, crisis status, formulation, glucose pattern, kidney function, concurrent medications, technique, monitoring, hypoglycemia treatment, and glucagon access.</span>`);}

function vancomycinTwoLevelPK(dose,tau,tinf,c1,t1,c2,t2,mic){
  const k=Math.log(c1/c2)/(t2-t1),half=0.693/k,cmax=c1*Math.exp(k*t1),toNext=tau-tinf-t2,cmin=c2*Math.exp(-k*toNext),rate=dose/tinf,vd=(rate*(1-Math.exp(-k*tinf)))/(k*(cmax-cmin*Math.exp(-k*tinf))),cl=k*vd,auc=dose*(24/tau)/cl;
  return {k,half,cmax,cmin,vd,cl,auc,aucMic:auc/mic,toNext};
}
function vancomycinTargetInterpretation(auc,aucMic,mic,context){
  if(context!=='serious')return {allowProjection:false,scope:'No universal 400–600 target is established by the 2020 consensus guideline for this indication; use organism, site, severity, and facility policy.'};
  if(Math.abs(mic-1)>0.001)return {allowProjection:false,scope:`Target classification is suppressed because the entered MIC is ${calcRound(mic,2)} mg/L. The consensus target is interpreted assuming broth-microdilution MIC = 1 mg/L. AUC/MIC is ${calcRound(aucMic,0)}, but do not escalate exposure simply to force a ratio of 400 when MIC is >1.`};
  return {allowProjection:true,scope:`Serious MRSA exposure is <b>${auc>=400&&auc<=600?'within':'outside'}</b> the 400–600 target (MIC assumed 1 mg/L).`};
}
function calcVancomycinAUC(){
  const dose=calcReadNumber('va_dose'),tau=calcReadNumber('va_tau'),tinf=calcReadNumber('va_tinf'),mic=calcReadNumber('va_mic'),c1=calcReadNumber('va_c1'),t1=calcReadNumber('va_t1'),c2=calcReadNumber('va_c2'),t2=calcReadNumber('va_t2'),context=document.getElementById('va_context')?.value,steady=calcReadBinary('va_steady'),stable=calcReadBinary('va_stable');
  if([dose,tau,tinf,mic,c1,t1,c2,t2].some(v=>v===null)||[dose,tau,tinf,mic,c1,c2].some(v=>v<=0)){setCalcResult('va_out','Enter positive dose, timing, concentrations, and MIC.');return;}
  if(!steady||!stable){setCalcResult('va_out','<b>Do not project a regimen with this static worksheet.</b><br>Two-level first-order equations assume near steady state and reasonably stable clearance. Use repeat levels, renal trend, and a validated Bayesian or local AKI protocol.');return;}
  if(t1<1||t1>2){setCalcResult('va_out','Level 1 must be a postdistributional sample collected 1–2 hours after the infusion ends for this two-level worksheet.');return;}
  if(!(c1>c2&&t2>t1&&t2<=(tau-tinf))){setCalcResult('va_out','Check sampling: level 1 must exceed level 2, t2 must follow t1, and both post-infusion times must fit within the interval.');return;}
  const r=vancomycinTwoLevelPK(dose,tau,tinf,c1,t1,c2,t2,mic);if(!Object.values(r).every(Number.isFinite)||r.k<=0||r.vd<=0||r.cl<=0){setCalcResult('va_out','These values do not produce physiologically usable first-order estimates. Verify exact administration and collection times.');return;}
  const tdd=dose*(24/tau),interpretation=vancomycinTargetInterpretation(r.auc,r.aucMic,mic,context),low=tdd*400/r.auc,high=tdd*600/r.auc;
  const projection=interpretation.allowProjection?`<br>Linear-PK teaching range for AUC 400–600: <b>${calcRound(low,0)}–${calcRound(high,0)} mg/day</b>. This is not an automatic regimen.`:'';
  setCalcResult('va_out',`AUC24 ≈ <b>${calcRound(r.auc,0)} mg·h/L</b> · AUC/MIC ≈ ${calcRound(r.aucMic,0)}<br>k ${calcRound(r.k,4)} h⁻¹ · t½ ${calcRound(r.half,1)} h · peak ${calcRound(r.cmax,1)} mg/L · trough ${calcRound(r.cmin,1)} mg/L<br>Vd ${calcRound(r.vd,1)} L · CL ${calcRound(r.cl,2)} L/h<br><span class="calc-note">${interpretation.scope}</span>${projection}`);
}
function calcVancomycinTrough(){
  const level=calcReadNumber('vt_level'),early=calcReadNumber('vt_early'),half=calcReadNumber('vt_half'),context=document.getElementById('vt_context')?.value;if([level,early,half].some(v=>v===null)||level<=0||early<0||half<=0){setCalcResult('vt_out','Enter a positive concentration and patient-specific half-life.');return;}
  const k=0.693/half,trueTrough=level*Math.exp(-k*early);let note;if(context==='serious')note='For serious invasive MRSA, do not increase the dose merely to force a 15–20 mg/L trough. Current consensus prefers AUC-guided monitoring.';else if(context==='hd')note='Intermittent HD is a guideline-supported exception: a predialysis 15–20 mg/L concentration is likely to correspond to AUC 400–600. Dose by measured concentration and the local dialysis protocol.';else note='The corrected trough can support a facility-defined workflow. The national guideline does not assign a universal trough target for noninvasive or non-MRSA infections.';
  setCalcResult('vt_out',`Extrapolated true trough ≈ <b>${calcRound(trueTrough,1)} mg/L</b><br>k = ${calcRound(k,4)} h⁻¹<br><span class="calc-note">${note}</span>`);
}

function ckdEpiCr2021(age,sex,scr){const k=sex==='f'?0.7:0.9,a=sex==='f'?-0.241:-0.302;return 142*Math.pow(Math.min(scr/k,1),a)*Math.pow(Math.max(scr/k,1),-1.2)*Math.pow(0.9938,age)*(sex==='f'?1.012:1);}
function ckdEpiCrCys2021(age,sex,scr,cys){const k=sex==='f'?0.7:0.9,a=sex==='f'?-0.219:-0.144;return 135*Math.pow(Math.min(scr/k,1),a)*Math.pow(Math.max(scr/k,1),-0.544)*Math.pow(Math.min(cys/0.8,1),-0.323)*Math.pow(Math.max(cys/0.8,1),-0.778)*Math.pow(0.9961,age)*(sex==='f'?0.963:1);}
function mostellerBSA(heightCm,weightKg){return Math.sqrt(heightCm*weightKg/3600);}
function cockcroftGault(age,sex,weight,scr){return ((140-age)*weight)/(72*scr)*(sex==='f'?0.85:1);}
function selectCockcroftEstimate(mode,actual,ideal,adjusted){if(mode==='actual')return {label:'actual weight',value:actual};if(mode==='ideal'&&ideal!==null)return {label:'ideal weight per selected protocol',value:ideal};if(mode==='adjusted'&&adjusted!==null)return {label:'AdjBW0.4 per selected obesity protocol',value:adjusted};return null;}
function cockcroftWeightOptions(heightCm,weightKg,sex){const heightIn=heightCm/2.54,ibw=heightIn>=60?((sex==='f'?45.5:50)+2.3*(heightIn-60)):null,bmi=weightKg/Math.pow(heightCm/100,2);return {ibw,idealAllowed:ibw!==null&&weightKg>=ibw,adjustedAllowed:ibw!==null&&bmi>=30,bmi};}
function updateCockcroftWeightOptions(){const height=calcReadNumber('rn_height'),weight=calcReadNumber('rn_weight'),sex=document.getElementById('rn_sex')?.value||'f',select=document.getElementById('rn_cg_weight');if(!select||!height||!weight)return;const rules=cockcroftWeightOptions(height,weight,sex),ideal=select.querySelector('option[value="ideal"]'),adjusted=select.querySelector('option[value="adjusted"]');if(ideal)ideal.disabled=!rules.idealAllowed;if(adjusted)adjusted.disabled=!rules.adjustedAllowed;if((select.value==='ideal'&&!rules.idealAllowed)||(select.value==='adjusted'&&!rules.adjustedAllowed))select.value='all';}
function kidneyStage(gfr){if(gfr>=90)return'G1';if(gfr>=60)return'G2';if(gfr>=45)return'G3a';if(gfr>=30)return'G3b';if(gfr>=15)return'G4';return'G5';}
function kdigoAkiStage(input){
  const baselineKnown=!!input.baselineKnown,baseline=Number(input.baseline),current=Number(input.current),scrHours=Number(input.scrHours),weight=Number(input.weight),urineVolume=Number(input.urineVolume),uoHours=Number(input.uoHours),anuriaHours=Number(input.anuriaHours)||0,rrt=!!input.rrt;
  let scrStage=null,scrCriterion='SCr component indeterminate',ratio=null,delta=null;
  if(baselineKnown&&baseline>0&&current>0&&scrHours>=0){
    ratio=current/baseline;delta=(Math.round(current*1000)-Math.round(baseline*1000))/1000;const absolute48=scrHours<=48&&Math.round(delta*1000)>=300,relative7=scrHours<=168&&ratio>=1.5,acute=absolute48||relative7;
    scrStage=0;if(acute){if(ratio>=3||(current>=4&&delta>=0.3))scrStage=3;else if(ratio>=2)scrStage=2;else scrStage=1;}
    scrCriterion=scrStage?`Stage ${scrStage}: SCr ${calcRound(ratio,2)}× baseline, Δ${calcRound(delta,2)} mg/dL over ${calcRound(scrHours,1)} h`:`No SCr criterion: ${calcRound(ratio,2)}× baseline, Δ${calcRound(delta,2)} mg/dL over ${calcRound(scrHours,1)} h`;
  }
  let uoStage=null,uoRate=null,uoCriterion='Urine-output component not supplied';
  const hasUo=weight>0&&urineVolume>=0&&uoHours>0;if(hasUo){uoRate=urineVolume/weight/uoHours;uoStage=0;if(uoRate<0.3&&uoHours>=24)uoStage=3;else if(uoRate<0.5&&uoHours>=12)uoStage=2;else if(uoRate<0.5&&uoHours>=6)uoStage=1;uoCriterion=uoStage?`Stage ${uoStage}: ${calcRound(uoRate,2)} mL/kg/h over ${calcRound(uoHours,1)} h`:`No UO criterion: ${calcRound(uoRate,2)} mL/kg/h over ${calcRound(uoHours,1)} h`;}
  if(anuriaHours>=12){uoStage=3;uoCriterion=`Stage 3: anuria for ${calcRound(anuriaHours,1)} h`;}
  const rrtStage=rrt?3:0,finalStage=Math.max(scrStage||0,uoStage||0,rrtStage),determining=[];if(finalStage&&scrStage===finalStage)determining.push('SCr');if(finalStage&&uoStage===finalStage)determining.push('urine output');if(finalStage&&rrtStage===finalStage)determining.push('new RRT');
  return {finalStage,scrStage,uoStage,rrtStage,scrCriterion,uoCriterion,uoRate,ratio,delta,determining};
}
function calcKdigoAki(){
  const source=document.getElementById('ak_base_source')?.value,baseline=calcReadNumber('ak_baseline'),current=calcReadNumber('ak_current'),scrHours=calcReadNumber('ak_scr_hours'),weight=calcReadNumber('ak_weight'),urineVolume=calcReadNumber('ak_urine'),uoHours=calcReadNumber('ak_uo_hours'),anuriaHours=calcReadNumber('ak_anuria')??0,rrt=calcReadBinary('ak_rrt');
  if(source==='measured'&&([baseline,current,scrHours].some(v=>v===null)||baseline<=0||current<=0||scrHours<0)){setCalcResult('ak_out','Enter positive measured baseline and current SCr values with a valid interval, or mark the baseline unknown.');return;}
  const anyUo=[weight,urineVolume,uoHours].some(v=>v!==null);if(anyUo&&([weight,urineVolume,uoHours].some(v=>v===null)||weight<=0||urineVolume<0||uoHours<=0)){setCalcResult('ak_out','For urine-output staging, enter weight, total urine volume, and a positive contiguous interval together.');return;}if(anuriaHours<0){setCalcResult('ak_out','Anuria duration cannot be negative.');return;}
  const result=kdigoAkiStage({baselineKnown:source==='measured',baseline,current,scrHours,weight,urineVolume,uoHours,anuriaHours,rrt});if(source!=='measured'&&!anyUo&&anuriaHours<12&&!rrt){setCalcResult('ak_out','SCr stage is indeterminate without a measured stable baseline. Add reliable urine-output data or new-RRT status; no baseline is inferred.');return;}
  const final=result.finalStage?`<b>KDIGO AKI Stage ${result.finalStage}</b>`:'<b>No KDIGO AKI criteria met with supplied data.</b>',rrtLine=rrt?'Stage 3: kidney replacement therapy newly initiated for this acute episode':'No new RRT criterion supplied';
  setCalcResult('ak_out',`${final}<br>${result.scrCriterion}<br>${result.uoCriterion}<br>${rrtLine}${result.finalStage?`<br><span class="calc-note">Determining criterion: ${result.determining.join(', ')}. Use the highest component stage.</span>`:'<br><span class="calc-note">Incomplete observation can miss AKI; this result does not exclude another cause or later progression.</span>'}`);
  if(result.finalStage){const renalFlag=document.getElementById('rn_aki');if(renalFlag)renalFlag.value='1';setCalcResult('rn_out','<b>Static kidney estimates suppressed.</b><br>KDIGO AKI criteria are met, so CKD-EPI and Cockcroft–Gault should not be treated as stable dosing endpoints. Use trends, urine output, measured clearance when feasible, TDM, and frequent reassessment.');}
}
function renalEstimateBlockReason(age,aki,preg){if(age<18||age>120)return 'Enter an adult age from 18 to 120 years.';if(aki&&preg)return 'Static CKD-EPI and Cockcroft–Gault estimates are suppressed because renal function is nonsteady and the patient is pregnant.';if(aki)return 'Static CKD-EPI and Cockcroft–Gault estimates are suppressed during AKI or rapidly changing SCr. Use the creatinine trend, urine output, measured clearance when feasible, TDM, and frequent reassessment.';if(preg)return 'Static CKD-EPI and Cockcroft–Gault estimates are suppressed because these adult equations are not validated for definitive pregnancy dosing. Use pregnancy-specific evidence or measured assessment.';return '';}
function calcRenalFunction(){
  const age=calcReadNumber('rn_age'),sex=document.getElementById('rn_sex')?.value,height=calcReadNumber('rn_height'),weight=calcReadNumber('rn_weight'),scr=calcReadNumber('rn_scr'),cys=calcReadNumber('rn_cys'),aki=calcReadBinary('rn_aki'),preg=calcReadBinary('rn_preg'),cgMode=document.getElementById('rn_cg_weight')?.value||'all';if([age,height,weight,scr].some(v=>v===null)||height<100||height>250||weight<20||weight>400||scr<=0){setCalcResult('rn_out','Enter age, plausible adult height and weight, and a positive SCr.');return;}if(cys!==null&&cys<=0){setCalcResult('rn_out','Cystatin C must be positive when supplied.');return;}
  const blocked=renalEstimateBlockReason(age,aki,preg);if(blocked){setCalcResult('rn_out',`<b>No numeric estimate displayed.</b><br>${blocked}`);return;}
  const weightRules=cockcroftWeightOptions(height,weight,sex),ibw=weightRules.ibw,adj=weightRules.adjustedAllowed?ibw+0.4*(weight-ibw):null,cgActual=cockcroftGault(age,sex,weight,scr),cgIdeal=weightRules.idealAllowed?cockcroftGault(age,sex,ibw,scr):null,cgAdj=adj!==null?cockcroftGault(age,sex,adj,scr):null,selected=selectCockcroftEstimate(cgMode,cgActual,cgIdeal,cgAdj);updateCockcroftWeightOptions();
  const egfr=ckdEpiCr2021(age,sex,scr),bsa=mostellerBSA(height,weight),absolute=egfr*bsa/1.73,combined=cys!==null?ckdEpiCrCys2021(age,sex,scr,cys):null;
  const warning=height/2.54<60?'<br><span class="calc-note">Height is below 5 ft, so this tool does not extrapolate the Devine IBW formula; use a patient- and protocol-specific weight method.</span>':!weightRules.adjustedAllowed?'<br><span class="calc-note">AdjBW0.4 is not shown because the obesity condition (BMI ≥30 kg/m²) is not met.</span>':'';
  const selectionNote=selected?`Explicit convention selected: ${selected.label} → ${calcRound(selected.value,1)} mL/min.`:'No Cockcroft–Gault weight convention selected. Compare estimates and choose only the drug label or local protocol-defined method.';
  setCalcResult('rn_out',`2021 CKD-EPI eGFRcr = <b>${calcRound(egfr,1)} mL/min/1.73 m²</b> · GFR category ${kidneyStage(egfr)}<br>Absolute eGFR ≈ <b>${calcRound(absolute,1)} mL/min</b> (BSA ${calcRound(bsa,2)} m²)${combined!==null?`<br>2021 eGFRcr-cys = <b>${calcRound(combined,1)} mL/min/1.73 m²</b>`:''}<br>Cockcroft–Gault: actual ${calcRound(cgActual,1)}${cgIdeal!==null?` · IBW ${calcRound(cgIdeal,1)} · AdjBW0.4 ${calcRound(cgAdj,1)}`:''} mL/min<br><span class="calc-note">${selectionNote} A GFR category alone does not diagnose CKD; chronicity ≥3 months plus cause and albuminuria complete KDIGO CGA classification.</span>${warning}`);
}

var OPIOID_GATE_APPROVED=false;
function opioidDosingGate(input){
  if(input.excluded||input.setting!=='outpatient'||input.formulation==='other'||input.organ==='unstable')return {code:'EXCLUDED_SPECIALIST_WORKFLOW',step:0,label:'Specialist or monitored workflow',allowRotation:false,text:'This population, route, setting, or unstable organ state is outside automated dose math. Do not use MME or equianalgesic arithmetic to create a regimen.'};
  if(input.formulation==='erla')return {code:'ERLA_CLINICIAN_ONLY_NO_AUTODOSE',step:1,label:'ER/LA request stopped',allowRotation:false,text:'Do not initiate with an ER/LA opioid or use ER/LA for acute or as-needed therapy. Product-specific eligibility and prescribing remain clinician-only.'};
  if(input.organ==='impaired')return {code:'ORGAN_IMPAIRMENT_CLINICIAN_ONLY',step:2,label:'Organ impairment requires manual dosing',allowRotation:false,text:'Stable renal or hepatic impairment requires label-specific lower starting exposure and close monitoring. Do not stack an automatic organ reduction onto a cross-tolerance reduction.'};
  if(input.cosedative||input.respiratory)return {code:'COSEDATIVE_CLINICIAN_REVIEW_NO_AUTODOSE',step:2,label:'Overdose-risk review required',allowRotation:false,text:'A CNS depressant, sleep/respiratory risk, or prior-overdose risk requires clinician review and naloxone planning. A low MME does not make the combination safe.'};
  if(input.status==='unstable')return {code:'INSUFFICIENT_DATA_NO_DOSE',step:2,label:'Use pattern is not stable',allowRotation:false,text:'Variable consumption or escalating pain cannot support a representative 24-hour rotation estimate.'};
  if(input.status==='naive'&&input.duration==='acute')return {code:'MANUAL_INITIATION_ONLY',step:3,label:'Opioid-naive acute pain',allowRotation:false,text:'Maximize nonopioid therapy first. If an opioid is chosen, use immediate release, the lowest effective dose, as-needed use when appropriate, and no more quantity than needed for the expected severe-pain duration. No drug or dose is selected here.'};
  if(input.status==='naive')return {code:'DO_NOT_AUTO_INITIATE_CHRONIC_OPIOID',step:3,label:'Opioid-naive subacute or chronic pain',allowRotation:false,text:'Nonopioid therapy is preferred. Require functional goals, benefit–risk discussion, and a discontinuation plan before any clinician-led trial.'};
  return {code:'BOUNDED_ROTATION_MATH_ALLOWED',step:4,label:'Limited oral IR rotation math',allowRotation:true,text:'A single stable oral immediate-release morphine, oxycodone, or hydromorphone regimen may proceed to raw Merck-equivalent math and a 50% educational cross-tolerance estimate. No schedule or prescription is generated.'};
}
function opioidDecisionTreeHTML(state){const steps=[['Scope exclusions','Adult outpatient, nonpregnant, noncancer, non-OUD, oral route, and stable clinical status only.'],['Formulation','Immediate release only; ER/LA and parenteral/PCA/neuraxial requests stop.'],['Safety review','Stable organ function, representative use, medication reconciliation, respiratory risk, and naloxone access.'],['Initiation guard','Opioid-naive initiation remains manual; nonopioid therapy is preferred for subacute or chronic pain.'],['Bounded calculation','Only stable oral IR morphine, oxycodone, or hydromorphone rotation math is shown.']];const current=state?.step;return `<section class="decision-tree" aria-label="Opioid dosing safety path"><div class="decision-tree-head"><div><b>Dosing safety path</b><span>${state?.text||'Run the scope check before any rotation calculation.'}</span></div>${state?`<strong>${state.code}</strong>`:''}</div><ol>${steps.map((s,i)=>`<li class="${current===i?'active':current!==undefined&&i<current?'done':''}" ${current===i?'aria-current="step"':''}><span>${i+1}</span><div><b>${s[0]}</b><p>${s[1]}</p></div></li>`).join('')}</ol></section>`;}
function readOpioidGateInputs(){return {setting:document.getElementById('og_setting')?.value,duration:document.getElementById('og_duration')?.value,status:document.getElementById('og_status')?.value,formulation:document.getElementById('og_formulation')?.value,organ:document.getElementById('og_organ')?.value,cosedative:!!calcReadBinary('og_cosedative'),respiratory:!!calcReadBinary('og_respiratory'),excluded:!!calcReadBinary('og_excluded')};}
function invalidateOpioidGate(){OPIOID_GATE_APPROVED=false;const btn=document.getElementById('or_calculate');if(btn)btn.disabled=true;const scope=opioidDosingGate(readOpioidGateInputs());setCalcResult('or_out','Scope answers changed. Run the Opioid Dosing Scope Check again before rotation math.');setCalcResult('op_out',scope.code==='EXCLUDED_SPECIALIST_WORKFLOW'?`<b>MME worksheet unavailable.</b><br>${scope.text}`:'Scope answers changed. Recalculate MME after reviewing the current setting and exclusions.');}
function calcOpioidDosingGate(){const input=readOpioidGateInputs(),state=opioidDosingGate(input);OPIOID_GATE_APPROVED=state.allowRotation;const btn=document.getElementById('or_calculate');if(btn)btn.disabled=!state.allowRotation;setCalcResult('og_out',`<b>${state.label}</b><br>${state.text}${input.cosedative||input.respiratory?'<br><span class="calc-note">Offer naloxone and review all CNS depressants.</span>':''}`);const flow=document.getElementById('og_flow');if(flow)flow.innerHTML=opioidDecisionTreeHTML(state);if(!state.allowRotation)setCalcResult('or_out','');}

const CDC_MME_FACTORS={codeine:0.15,fentanyl_patch:2.4,hydrocodone:1,hydromorphone:5,methadone:4.7,morphine:1,oxycodone:1.5,oxymorphone:3,tapentadol:0.4,tramadol:0.2};
const OPIOID_NAMES={codeine:'Codeine',fentanyl_patch:'Fentanyl patch',hydrocodone:'Hydrocodone',hydromorphone:'Hydromorphone',methadone:'Methadone',morphine:'Morphine',oxycodone:'Oxycodone',oxymorphone:'Oxymorphone',tapentadol:'Tapentadol',tramadol:'Tramadol'};
function opioidMME(drug,dose){return dose*(CDC_MME_FACTORS[drug]||0);}
function incompleteOpioidRows(rows){return rows.map((r,i)=>r.drug&&r.drug!=='none'&&(r.dose===null||r.dose<=0)?i+1:null).filter(Boolean);}
function calcOpioidMME(){
  const scope=opioidDosingGate(readOpioidGateInputs());if(scope.code==='EXCLUDED_SPECIALIST_WORKFLOW'){setCalcResult('op_out',`<b>MME worksheet unavailable.</b><br>${scope.text}`);return;}
  const entered=[1,2,3].map(i=>({drug:document.getElementById('op_drug'+i)?.value,dose:calcReadNumber('op_dose'+i)})),incomplete=incompleteOpioidRows(entered);if(incomplete.length){setCalcResult('op_out',`Enter a positive daily dose for opioid row${incomplete.length>1?'s':''} ${incomplete.join(', ')}.`);return;}const rows=entered.filter(r=>r.drug&&r.drug!=='none');if(!rows.length){setCalcResult('op_out','Enter at least one current opioid and total daily dose.');return;}
  const parts=rows.map(r=>({drug:r.drug,dose:r.dose,mme:opioidMME(r.drug,r.dose)})),total=parts.reduce((s,r)=>s+r.mme,0),detail=parts.map(r=>`${OPIOID_NAMES[r.drug]} ${r.dose}${r.drug==='fentanyl_patch'?' mcg/hr':' mg/day'} × ${CDC_MME_FACTORS[r.drug]} = ${calcRound(r.mme,1)} MME/day`).join('<br>');
  let note=total>=50?'Before further escalation, reassess benefits and risks, increase follow-up, review co-sedatives, and offer naloxone. This is not a rigid ceiling or forced-taper trigger.':'MME below 50 does not establish safety; assess sedation, respiratory risk, organ function, interactions, and indication.';
  if(parts.some(r=>r.drug==='methadone'))note+=' Methadone 4.7 is for risk comparison only and must not be reversed into an opioid-rotation dose.';if(parts.some(r=>r.drug==='fentanyl_patch'))note+=' The fentanyl factor applies only to transdermal mcg/hour, not other fentanyl formulations.';
  setCalcResult('op_out',`${detail}<br>Total daily exposure = <b>${calcRound(total,1)} MME/day</b><br><span class="calc-note">${note}</span>`);
}
const ROTATION_EQUIANALGESIC={morphine:{name:'Morphine PO',dose:30},oxycodone:{name:'Oxycodone PO',dose:20},hydromorphone:{name:'Hydromorphone PO',dose:7.5}};
function opioidRotationEstimate(from,dose,to){const source=ROTATION_EQUIANALGESIC[from],target=ROTATION_EQUIANALGESIC[to],equianalgesic=dose/source.dose*target.dose;return {equianalgesic,reduced:equianalgesic*0.5};}
function calcOpioidRotation(){
  const gate=opioidDosingGate(readOpioidGateInputs());if(!OPIOID_GATE_APPROVED||!gate.allowRotation){OPIOID_GATE_APPROVED=false;const btn=document.getElementById('or_calculate');if(btn)btn.disabled=true;setCalcResult('or_out',`Rotation math blocked: ${gate.text||'run and pass the Opioid Dosing Scope Check again.'}`);return;}
  const from=document.getElementById('or_from')?.value,to=document.getElementById('or_to')?.value,dose=calcReadNumber('or_dose');if(!ROTATION_EQUIANALGESIC[from]||!ROTATION_EQUIANALGESIC[to]||dose===null||dose<=0){setCalcResult('or_out','Choose supported oral opioids and enter representative actual 24-hour consumption.');return;}if(from===to){setCalcResult('or_out','Choose a different target opioid.');return;}
  const r=opioidRotationEstimate(from,dose,to),s=ROTATION_EQUIANALGESIC[from],t=ROTATION_EQUIANALGESIC[to];setCalcResult('or_out',`Raw single-dose table estimate: ${dose} mg/day ${s.name} × (${t.dose}/${s.dose}) = <b>${calcRound(r.equianalgesic,1)} mg/day ${t.name}</b><br>50% educational cross-tolerance estimate: <b>${calcRound(r.reduced,1)} mg/day</b><br><span class="calc-note">This is not a prescription or final dose. A clinician must choose formulation, interval, tablet rounding, rescue plan, monitoring, and whether a different reduction is needed. Methadone, fentanyl, buprenorphine, organ impairment, co-sedatives, and unstable pain are excluded.</span>`);
}
/* CLINICAL_CALCULATORS_LOGIC_END */

var CLINICAL_CALCULATOR_RETURN_FOCUS=null;
function calculatorFocusable(root){return [...root.querySelectorAll('button:not([disabled]),input:not([disabled]),select:not([disabled]),a[href],[tabindex]:not([tabindex="-1"])')].filter(el=>el.offsetParent!==null);}
function trapCalculatorFocus(e,root){if(e.key!=='Tab')return;const items=calculatorFocusable(root);if(!items.length)return;const first=items[0],last=items[items.length-1];if(!root.contains(document.activeElement)){e.preventDefault();(e.shiftKey?last:first).focus();return;}if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}
function clinicalCalculatorDialogKeydown(e){const ov=document.getElementById('calcToolOv');if(!ov||document.getElementById('calculatorConceptOv'))return;if(e.key==='Escape'){e.preventDefault();closeClinicalCalculator();return;}trapCalculatorFocus(e,ov);}
function activateClinicalCalculatorDialog(ov,focus,returnFocus){CLINICAL_CALCULATOR_RETURN_FOCUS=returnFocus||document.activeElement;ov.setAttribute('role','dialog');ov.setAttribute('aria-modal','true');const h=ov.querySelector('.calc-tool-head h3'),close=ov.querySelector('.calc-tool-head button'),card=focus?ov.querySelector(`.calc-tool[data-tool="${focus}"]`):null,target=card?.querySelector('h4')||close;if(h){h.id='clinicalCalculatorTitle';ov.setAttribute('aria-labelledby',h.id);}if(close)close.id='clinicalCalculatorClose';if(card){card.classList.add('focus');if(target)target.tabIndex=-1;}document.removeEventListener('keydown',clinicalCalculatorDialogKeydown);document.addEventListener('keydown',clinicalCalculatorDialogKeydown);setTimeout(()=>{card?.scrollIntoView({block:'center'});target?.focus();},20);}
function deactivateClinicalCalculatorDialog(restoreFocus=true){document.removeEventListener('keydown',clinicalCalculatorDialogKeydown);if(typeof closeCalculatorConcept==='function')closeCalculatorConcept(false);const saved=CLINICAL_CALCULATOR_RETURN_FOCUS;CLINICAL_CALCULATOR_RETURN_FOCUS=null;if(restoreFocus&&saved)setTimeout(()=>{const target=saved==='resident-tools'?document.querySelector('[aria-label="Resident tools"]'):saved;if(target&&target.isConnected)target.focus();},20);}
