import fs from 'node:fs';

const demo = fs.readFileSync(new URL('../demo.html', import.meta.url), 'utf8');
const home = fs.readFileSync(new URL('../index.html', import.meta.url), 'utf8');
const checks = [];
const add = (name, pass, detail='') => checks.push({name, pass:Boolean(pass), detail});

add('Marketing rotation count is current', home.includes('<b>69</b>&nbsp;guided rotations'));
add('Marketing case count is current', home.includes('<b>1,051</b>&nbsp;clinical cases'));
add('Persistent simulation disclaimer', demo.includes('No medical advice, residency credit, credentialing, or independent-practice validation') && demo.includes('body.case-active #app{height:calc(100dvh - 52px)') && demo.includes('@media(max-width:900px)'));
add('No credential-conferring result label', !/PGY-1 Graduate|Ready for BCPS \/ PGY-2/.test(demo));
add('Critical-response remediation gate', demo.includes('criticalMisses().length'));
add('Readiness review is formative', demo.includes('No medical advice, residency credit, credentialing, or independent-practice validation'));
add('Content governance surface is removed', !demo.includes('CONTENT_GOVERNANCE') && !demo.includes('Content Governance'));
add('R1-R4 and Core explanations live in Pip, not a standalone map dialog', demo.includes('function pipCompetencyGuide(q)') && demo.includes("hub:[['R1–R4 / Core','rotation labels']") && demo.includes('ASHP PGY-1 competency areas') && !demo.includes('What do R1 and Core mean?') && !demo.includes('showCompetencyHelp'));
add('Learning-experience structure banner is removed', !demo.includes('Learning experience structure:'));
add('Current DKA potassium threshold', demo.includes('K⁺ &lt; 3.5') && !demo.includes('K⁺ &lt; 3.3') && !demo.includes('K⁺ ≥ 3.3'));
add('Keyboard skip links', demo.includes('Skip to simulation content') && home.includes('Skip to main content'));
add('Visible keyboard focus', demo.includes(':focus-visible') && home.includes(':focus-visible'));
add('No remote character CDN dependency', !demo.includes('d8j0ntlcm91z4.cloudfront.net') && !home.includes('d8j0ntlcm91z4.cloudfront.net'));
add('69-rotation map present', demo.includes('Residency Roadmap') && demo.includes('View all ${MODULES.length} rotations'));
add('Code Stroke validation present', demo.includes('code_stroke_validation'));
add('P&T committee module present', demo.includes('pt_med_safety_committee'));
add('Informatics module present', demo.includes('informatics_surveillance'));
add('Equity/reflection module present', demo.includes('communication_equity_reflection'));
add('Hub guard prevents no-game trap', demo.includes("if(typeof G==='undefined'||!G||!G.results){showTitle();return;}"));
add('Back navigation returns to previous screen', demo.includes('function goBack(') && demo.includes('function navPush('));
add('Practice-record download menu removed (per product decision)', !demo.includes('Download practice record'));
add('Competency CSV export wired to UI', demo.includes('exportCompetencyCSV()'));
add('Competency JSON export wired to UI', demo.includes('exportCompetencyJSON()'));
add('CSV export includes critical-miss column', demo.includes("'critical_misses'"));
add('Readiness cards use per-area critical status', demo.includes('critByArea'));
add('Study Cards use a 20-card queue', demo.includes('studyDueCandidates().slice(0,20)') && demo.includes('<span>Today</span>'));
add('Completion score preserves decimal precision', demo.includes('displayPct(c,t)') && demo.includes('ov.displayPct'));
add('Safety note leaves helper-button clearance', demo.includes('right:72px'));
add('MCQ correct positions are deterministically balanced', demo.includes('balanceMCQCorrectPositions()'));
add('Every MCQ is expanded to five options', demo.includes('ensureFiveMCQOptions'));
add('One coached MCQ retry is implemented', demo.includes('Try once more.') && demo.includes('c._attempts<2'));
add('Case selections can be cancelled', demo.includes('clearMcqSelection') && demo.includes('ondblclick'));
add('Case workspace prevents question overlap', demo.includes('case-workspace') && demo.includes('body.case-active .vn-wrap'));
add('Desktop case workspace uses a cohesive 70/30 two-column layout', demo.includes('grid-template-columns:minmax(0,7fr) minmax(300px,3fr)') && demo.includes('.case-main{grid-column:1}') && demo.includes('.case-side{grid-column:2}') && demo.includes('@media(max-width:920px)'));
const caseStemFn=(demo.match(/function caseStemHTML\(c\)\{[^\n]+/)||[])[0]||'';
add('Pip hint is anchored beside the question, not inside answers', caseStemFn.includes('case-question-body') && caseStemFn.includes('data-case-pip') && !demo.includes('class="hint-row"'));
add('Floating Pip is available in case mode and hides while its panel is open', demo.includes('body.case-active #pipBtn{display:block}') && demo.includes('body.case-active #pipBtn.on{display:none}'));
add('Glossary definitions open by click without hover collisions', demo.includes("tip.setAttribute('role','tooltip')") && demo.includes("span.setAttribute('aria-describedby',tipId)") && demo.includes('.abbr.open .abbr-tip{display:block}') && !demo.includes('.abbr:hover .abbr-tip'));
add('Drug names use static accessible emphasis without hover popups', demo.includes('function enhanceDrugTerms(root)') && demo.includes("span.setAttribute('role','term')") && demo.includes("span.setAttribute('aria-label',display+', medication')") && !demo.includes('text-decoration-line:underline') && !demo.includes('.drug-tip{') && !demo.includes("className='drug-tip'"));
add('Expanded medication references avoid repeated highlights and show medication sources', demo.includes("p.closest('.abbr,.abbr-tip,.drug-term,.drug-mono") && demo.includes('class="mono-sources"') && demo.includes('Medication source') && demo.includes('FDA prescribing information via DailyMed'));
add('Medication focus follows chips, key points, then aligned details', demo.includes('med-focus-drugs') && demo.includes('med-focus-points') && demo.includes('.mono-disclosure>summary{display:flex') && demo.includes('.mono-head{display:flex;flex-direction:column') && demo.includes('.mono-row{display:block'));
add('Long clinical terms wrap inside narrow medication columns', demo.includes('.mono-v{display:block;min-width:0;') && demo.includes('overflow-wrap:anywhere'));
add('Drug cards add to Study Cards and Quizlet export is centralized', demo.includes('addDrugToStudyCards') && demo.includes('exportQuizletTXT') && demo.includes('Export to Quizlet') && !demo.includes('Quizlet this drug') && !demo.includes('downloadCurrentQuizlet'));
add('Reference cards name the guideline, framework, or label publisher', demo.includes('function referenceSourceLine(r)') && demo.includes('Guideline source') && demo.includes('Label source') && demo.includes('Framework source') && demo.includes('referenceLinkHTML'));
add('Surface-aware MAR and chart review are present', demo.includes("function chartSurface(c)") && demo.includes("Medication Administration Record") && demo.includes('mar-grid'));
add('MAR timing and status are authored, not index-generated', demo.includes('AUTHORED_MAR_CASES') && demo.includes('function authoredMar(c)') && !demo.includes('function marTime(i)') && !demo.includes('function marStatus(i,row)'));
add('Mobile MAR fits without horizontal scrolling', demo.includes('.ehr-win{min-width:0;width:100%;max-width:100%}') && demo.includes('.case-main{overflow-x:visible}') && demo.includes('.mar-grid .ord-text,.mar-grid .mar-note{min-width:0}'));
add('Tablet MAR uses a compact four-column grid', demo.includes('.ehr-orders .mar-grid,.mar-grid.mar-head{grid-template-columns:72px minmax(200px,1fr) 82px minmax(140px,1fr)}'));
const journalAnswerFn=(demo.match(/function jcAnswerNnt\(i\)\{[\s\S]*?\n\}/)||[])[0]||'';
add('All item types use missed-case tracking', journalAnswerFn.includes('commitCaseResult(ok)') && journalAnswerFn.includes("saveProgress('case')"));
add('Review-mode position persists across reload', demo.includes('reviewMode:REVIEW_MODE||G.reviewMode||null') && demo.includes('d.reviewMode.moduleId===curM.id'));
add('Pip helper is on the right', demo.includes('#pipBtn{position:fixed;right:16px;left:auto'));
const pipPanelFn=(demo.match(/function pipPanelHTML\(intro\)\{[\s\S]*?\n\}/)||[])[0]||'';
add('Pip panel follows the current page with three focused actions', demo.includes('function pipContextActions(sc)') && demo.includes('function pipContextMeta(sc)') && demo.includes('Helpful on this page'));
add('Pip panel omits team grid, duplicate tools, and volume', !pipPanelFn.includes('pipTeamHTML') && !pipPanelFn.includes('pip-actions') && !pipPanelFn.includes('volumeSliderHTML'));
add('Pip capture label is not written into notes', !demo.includes('line=`Pip capture:'));
add('Clinical reference catalog uses exact current U.S. sources', demo.includes('2026 AHA/ASA Acute Ischemic Stroke Guideline') && demo.includes('2026 ACC/AHA Guideline on the Management of Dyslipidemia') && demo.includes('SCCM 2025 Focused Update to the PADIS Guideline') && demo.includes('NHLBI 2020 Focused Updates to the Asthma Management Guidelines') && demo.includes('Best Possible Medication History (BPMH) Quick Tips'));
add('Known broad or dead reference URLs are absent', !demo.includes('surviving-sepsis-campaign-guidelines-2021') && !demo.includes('Guideline-Topic-Areas/Antithrombotic-Therapy') && !demo.includes('practice-guideline/practice-guidelines/') && !demo.includes('antibiotic-use/core-elements/hospital.html') && !demo.includes("['NABP Resources','https://nabp.pharmacy/']"));
add('Map return-to-case path is present and persisted', demo.includes('resumeCurrentCase()') && demo.includes('Return to paused case') && demo.includes('clinicalPathPausedCase'));
add('MAP and SSC glossary definitions are present', demo.includes("MAP:['Mean Arterial Pressure'") && demo.includes("SSC:['Surviving Sepsis Campaign'"));
add('Sound volume is adjustable and persisted', demo.includes('clinicalPathVolume') && demo.includes('data-vol-range') && demo.includes('setVolume(this.value,event)'));
add('Volume scales the audio engine gain', demo.includes('(gain||0.045)*SND.vol'));
add('Pip has a free-text ask box', demo.includes('id="pipAskInput"') && demo.includes('return pipAsk(event)'));
add('Pip local answer engine covers drugs, labs, glossary, rotations', demo.includes('function pipAnswer') && demo.includes('drugPool.find') && demo.includes('LAB_VALUES.filter') && demo.includes('Rotations matching'));
add('Pip escapes user input before echoing', demo.includes('function pipEsc'));

for (const c of checks) console.log(`${c.pass ? 'PASS' : 'FAIL'}  ${c.name}${c.detail ? ` — ${c.detail}` : ''}`);
const failed = checks.filter(c => !c.pass);
console.log(`\n${checks.length - failed.length}/${checks.length} checks passed`);
if (failed.length) process.exit(1);
