import fs from 'node:fs';

const demo = fs.readFileSync(new URL('../demo.html', import.meta.url), 'utf8');
const home = fs.readFileSync(new URL('../index.html', import.meta.url), 'utf8');
const checks = [];
const add = (name, pass, detail='') => checks.push({name, pass:Boolean(pass), detail});

add('Marketing rotation count is current', home.includes('<b>69</b>&nbsp;guided rotations'));
add('Marketing case count is current', home.includes('<b>457</b>&nbsp;clinical cases'));
add('Persistent simulation disclaimer', demo.includes('No medical advice, residency credit, credentialing, or independent-practice validation') && demo.includes('body.case-active #app{height:calc(100dvh - 52px)') && demo.includes('@media(max-width:900px)'));
add('No credential-conferring result label', !/PGY-1 Graduate|Ready for BCPS \/ PGY-2/.test(demo));
add('Critical-response remediation gate', demo.includes('criticalMisses().length'));
add('Readiness review is formative', demo.includes('No medical advice, residency credit, credentialing, or independent-practice validation'));
add('Content governance surface is removed', !demo.includes('CONTENT_GOVERNANCE') && !demo.includes('Content Governance'));
add('R1 and Core explanation is available on the year map', demo.includes('What do R1 and Core mean?') && demo.includes('function showCompetencyHelp()') && demo.includes('ASHP PGY-1 competency areas'));
add('Learning-experience structure banner is removed', !demo.includes('Learning experience structure:'));
add('Current DKA potassium threshold', demo.includes('K⁺ &lt; 3.5') && !demo.includes('K⁺ &lt; 3.3') && !demo.includes('K⁺ ≥ 3.3'));
add('Keyboard skip links', demo.includes('Skip to simulation content') && home.includes('Skip to main content'));
add('Visible keyboard focus', demo.includes(':focus-visible') && home.includes(':focus-visible'));
add('No remote character CDN dependency', !demo.includes('d8j0ntlcm91z4.cloudfront.net') && !home.includes('d8j0ntlcm91z4.cloudfront.net'));
add('69-rotation map present', demo.includes('Resident Year Map') && demo.includes('View all ${MODULES.length} rotations'));
add('Code Stroke validation present', demo.includes('code_stroke_validation'));
add('P&T committee module present', demo.includes('pt_med_safety_committee'));
add('Informatics module present', demo.includes('informatics_surveillance'));
add('Equity/reflection module present', demo.includes('communication_equity_reflection'));
add('Hub guard prevents no-game trap', demo.includes("if(typeof G==='undefined'||!G||!G.results){showTitle();return;}"));
add('Study Cards back label is context-aware', demo.includes("?'Back to year map':'Back to title'"));
add('Practice-record download menu is user-facing', demo.includes('Download practice record') && demo.includes('Spreadsheet file') && demo.includes('Structured data file'));
add('Competency CSV export wired to UI', demo.includes('exportCompetencyCSV()'));
add('Competency JSON export wired to UI', demo.includes('exportCompetencyJSON()'));
add('CSV export includes critical-miss column', demo.includes("'critical_misses'"));
add('Readiness cards use per-area critical status', demo.includes('critByArea'));
add('Study Cards use a 20-card queue', demo.includes('studyDueCandidates().slice(0,20)') && demo.includes('<span>Today</span>'));
add('Completion score preserves decimal precision', demo.includes('displayPct(c,t)') && demo.includes('ov.displayPct'));
add('Safety note leaves helper-button clearance', demo.includes('right:72px'));
add('MCQ correct positions are deterministically balanced', demo.includes('balanceMCQCorrectPositions()'));
add('Every MCQ is expanded to five options', demo.includes('ensureFiveMCQOptions'));
add('One coached MCQ retry is implemented', demo.includes('Try once more.') && demo.includes('c._attempts<2'));
add('Case selections can be cancelled', demo.includes('clearMcqSelection') && demo.includes('ondblclick'));
add('Case workspace prevents question overlap', demo.includes('case-workspace') && demo.includes('body.case-active .vn-wrap'));
add('Desktop case question remains viewport-centered', demo.includes('grid-template-columns:minmax(260px,310px) minmax(0,920px) minmax(260px,310px)') && demo.includes('.case-main{grid-column:2}') && demo.includes('.case-side{grid-column:3}'));
const caseStemFn=(demo.match(/function caseStemHTML\(c\)\{[^\n]+/)||[])[0]||'';
add('Case header has no duplicate Pip launcher', !caseStemFn.includes('data-case-pip') && !caseStemFn.includes('>Pip<'));
add('Floating Pip remains visible in case mode', demo.includes('body.case-active #pipBtn{display:block}'));
add('Glossary terms have direct hover and focus tooltips without badges', demo.includes("tip.setAttribute('role','tooltip')") && demo.includes("span.setAttribute('aria-describedby',tipId)") && !demo.includes("q.textContent=calc?'calc':'?'") && !demo.includes('.abbr-q{'));
add('Medication references and Quizlet actions are present', demo.includes('caseReferences(c)') && demo.includes('downloadCurrentQuizlet'));
add('Surface-aware MAR and chart review are present', demo.includes("function chartSurface(c)") && demo.includes("Medication Administration Record") && demo.includes('mar-grid'));
add('MAR timing and status are authored, not index-generated', demo.includes('AUTHORED_MAR_CASES') && demo.includes('function authoredMar(c)') && !demo.includes('function marTime(i)') && !demo.includes('function marStatus(i,row)'));
add('Mobile MAR fits without horizontal scrolling', demo.includes('.ehr-win{min-width:0;width:100%;max-width:100%}') && demo.includes('.case-main{overflow-x:visible}') && demo.includes('.mar-grid .ord-text,.mar-grid .mar-note{min-width:0}'));
add('Tablet MAR uses a compact four-column grid', demo.includes('.ehr-orders .mar-grid,.mar-grid.mar-head{grid-template-columns:72px minmax(200px,1fr) 82px minmax(140px,1fr)}'));
const journalAnswerFn=(demo.match(/function jcAnswerNnt\(i\)\{[\s\S]*?\n\}/)||[])[0]||'';
add('All item types use missed-case tracking', journalAnswerFn.includes('commitCaseResult(ok)') && journalAnswerFn.includes("saveProgress('case')"));
add('Review-mode position persists across reload', demo.includes('reviewMode:REVIEW_MODE||G.reviewMode||null') && demo.includes('d.reviewMode.moduleId===curM.id'));
add('Pip helper is on the right', demo.includes('#pipBtn{position:fixed;right:16px;left:auto'));
const pipPanelFn=(demo.match(/function pipPanelHTML\(intro\)\{[\s\S]*?\n\}/)||[])[0]||'';
add('Pip panel follows the current page with three focused actions', demo.includes('function pipContextActions(sc)') && demo.includes('function pipContextMeta(sc)') && demo.includes('Helpful on this page'));
add('Pip panel omits team grid, duplicate tools, and volume', !pipPanelFn.includes('pipTeamHTML') && !pipPanelFn.includes('pip-actions') && !pipPanelFn.includes('volumeSliderHTML'));
add('Pip capture label is not written into notes', !demo.includes('line=`Pip capture:'));
add('Clinical reference catalog uses exact current sources', demo.includes('Surviving Sepsis Campaign International Guidelines 2026') && demo.includes('2026 AHA/ASA Acute Ischemic Stroke Guideline') && demo.includes('2026 ACC/AHA Guideline on the Management of Dyslipidemia') && demo.includes('SCCM 2025 Focused Update to the PADIS Guideline') && demo.includes('PGY1-Harmonized-CAGO-COC-BOD-Approved-2025-0918.pdf'));
add('Known broad or dead reference URLs are absent', !demo.includes('surviving-sepsis-campaign-guidelines-2021') && !demo.includes('Guideline-Topic-Areas/Antithrombotic-Therapy') && !demo.includes('practice-guideline/practice-guidelines/') && !demo.includes('antibiotic-use/core-elements/hospital.html') && !demo.includes("['NABP Resources','https://nabp.pharmacy/']"));
add('Map return-to-case path is present and persisted', demo.includes('resumeCurrentCase()') && demo.includes('Return to paused case') && demo.includes('clinicalPathPausedCase'));
add('MAP and SSC glossary definitions are present', demo.includes("MAP:['Mean Arterial Pressure'") && demo.includes("SSC:['Surviving Sepsis Campaign'"));
add('Sound volume is adjustable and persisted', demo.includes('clinicalPathVolume') && demo.includes('data-vol-range') && demo.includes('setVolume(this.value,event)'));
add('Volume scales the audio engine gain', demo.includes('(gain||0.045)*SND.vol'));
add('Pip has a free-text ask box', demo.includes('id="pipAskInput"') && demo.includes('return pipAsk(event)'));
add('Pip local answer engine covers drugs, labs, glossary, rotations', demo.includes('function pipAnswer') && demo.includes('drugPool.find') && demo.includes('LAB_VALUES.filter') && demo.includes('Rotations matching'));
add('Pip escapes user input before echoing', demo.includes('function pipEsc'));

for (const c of checks) console.log(`${c.pass ? 'PASS' : 'FAIL'}  ${c.name}${c.detail ? ` — ${c.detail}` : ''}`);
const failed = checks.filter(c => !c.pass);
console.log(`\n${checks.length - failed.length}/${checks.length} checks passed`);
if (failed.length) process.exit(1);
